/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Controlador.FormatoTabla;
import Modelo.Bitacora;
import Modelo.Huesped;
import Modelo.TablaModelo;
import Modelo.Usuario;
import Modelo.Utilerias;
import java.awt.Cursor;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Usuario
 */
public class CnsClientes extends javax.swing.JInternalFrame
{
    private Huesped Cliente = null;
    //private DefaultTableModel dtmTabla;
    private TablaModelo dtmTabla;
    private Utilerias uAccesibilidad = null;    
    private Usuario uUsuario = Usuario.ObtenInstancia();
    private Bitacora uBitacora = Bitacora.ObtenInstancia();
    /**
     * Creates new form CnsClientes
     */
    public CnsClientes()
    {
        initComponents();        
        Cliente = new Huesped();
        uAccesibilidad = new Utilerias();        
        RefrescarForma();
        HabilitaComponentesUsuario();        
    }

    public void HabilitaComponentesUsuario()
    {
        if ( uUsuario.getTipo() != 0 )
        {
            btnEliminar.setEnabled(false);
        }
        else
        {
            btnEliminar.setEnabled(true);
        }
    }
    
    public void RefrescarForma()
    {
        try
        {                      
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));  
            tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tblClientes.doLayout();                        
            //dtmTabla = new DefaultTableModel(null, GetColumnas());
            dtmTabla = new TablaModelo(null, GetColumnas());
            tblClientes.setDefaultRenderer (Object.class, new FormatoTabla() );
            InicializarFilas();            
            tblClientes.setModel(dtmTabla);
            AjustaColumnas();         
            this.setCursor(Cursor.getDefaultCursor());    
            tblClientes.changeSelection(0, 1, false, false);
        }
        catch ( Exception e )
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al llenar el Catálogo");
        }
    }
    
    public void AjustaColumnas()
    {
        TableColumnModel tblModeloColumnas = tblClientes.getColumnModel();
        
        tblModeloColumnas.getColumn(0).setPreferredWidth(90);
        tblModeloColumnas.getColumn(1).setPreferredWidth(250);
        tblModeloColumnas.getColumn(2).setPreferredWidth(90);        
        tblModeloColumnas.getColumn(3).setPreferredWidth(300);
        tblModeloColumnas.getColumn(4).setPreferredWidth(90);
        tblModeloColumnas.getColumn(5).setPreferredWidth(90);
        tblModeloColumnas.getColumn(6).setPreferredWidth(90);                
    }
    
    public void InicializarFilas()
    {                
        //bdConexion = BDComunicador.ObtenInstancia();                                     
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //this.TotalRegistros = bdConexion.ObtenerTuplasRadiografiaCobranza(dtmTabla, getColumnas(), DameSentenciaSQL(), this.Sucursal);    
        Cliente.DameRegistrosCnsClientes(dtmTabla, GetColumnas());
        //EscribeNumRegistros();
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    public String[] GetColumnas()
    {                
        String strColumnas[] = new String[]{"Clave"/*0*/, "Nombre"/*1*/, "RFC"/*2*/, "Dirección"/*3*/, "Teléfono"/*4*/, "Nacionalidad"/*5*/, "Procedencia"/*6*/ };
        
        return strColumnas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jToolBar1 = new javax.swing.JToolBar();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta - Clientes");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAgregar.setToolTipText("Agregar");
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgregar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/type_string.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gnome_edit_delete.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);
        jToolBar1.add(jSeparator1);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door_in.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        AgregaHuesped();
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void AgregaHuesped()
    {
        FrmDetCliente frm = new FrmDetCliente(null, true);
        
        frm.show();
        RefrescarForma();
    }
    
    public void LlamaFormaEdicionHuesped(int iID)
    {
        FrmDetCliente frm = new FrmDetCliente(null, true, iID);
        
        frm.show();
        RefrescarForma();
    }
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        EditaHuesped();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        EliminaHuesped();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblClientesMouseClicked
    {//GEN-HEADEREND:event_tblClientesMouseClicked
        // TODO add your handling code here:        
        if ( evt.getClickCount() == 2 )
        {
            EditaHuesped();
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    public void EliminaHuesped()
    {
        int iID = 0;
        
        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Deseas realmente eliminar al huesped seleccionado?") == 0 )
        {
            if ( tblClientes != null )
            {    
                iID = Integer.parseInt(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString());
                Cliente.setId(iID);
                
                if ( Cliente.Eliminar() )
                {
                    uAccesibilidad.MuestraMensaje("Huesped eliminado correctamente.");
                    uBitacora.InsertarAccion(uUsuario.getID(), "EL USUARIO: " + uUsuario.getNomUsuario() + " ELIMINÓ USUARIO" , "CONSULTA DE HUESPEDES", Bitacora.ELIMINAR_CLIENTE);
                    RefrescarForma();
                }
                else
                {
                    uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de eliminar al Huesped.");
                }
            }
        }
    }
    
    public void Salir()
    {
        this.dispose();
    }
    
    public void EditaHuesped()
    {
        int iID = 0;
        
        if ( tblClientes != null )
        {    
            iID = Integer.parseInt(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString());
            LlamaFormaEdicionHuesped(iID);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
