/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Controlador.FormatoTabla;
import Modelo.Bitacora;
import Modelo.Descuento;
import Modelo.TablaModelo;
import Modelo.Usuario;
import Modelo.Utilerias;
import java.awt.Cursor;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Usuario
 */
public class CnsEmpresasDescuentos extends javax.swing.JInternalFrame
{
    private Descuento EmpresasDescuento;
    private Utilerias uAccesibilidad;
    private TablaModelo dtmTabla;
    private Usuario uUsuario = Usuario.ObtenInstancia();
    private Bitacora uBitacora = Bitacora.ObtenInstancia();
    /**
     * Creates new form CnsClientes
     */
    public CnsEmpresasDescuentos()
    {
        initComponents();        
        EmpresasDescuento = new Descuento();
        uAccesibilidad = new Utilerias();
        RefrescarForma();
        HabilitaComponentesUsuario();
        tblClientes.changeSelection(0, 1, false, false);
    }

    public void RefrescarForma()
    {
        try
        {                                  
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));  
            tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tblClientes.doLayout();                        
            dtmTabla = new TablaModelo(null, GetColumnas());                        
            tblClientes.setDefaultRenderer (Object.class, new FormatoTabla() );
            InicializarFilas();            
            tblClientes.setModel(dtmTabla);            
            tblClientes.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
            AjustaColumnas();         
            this.setCursor(Cursor.getDefaultCursor());
            tblClientes.changeSelection(0, 1, false, false);
        }
        catch ( Exception e )
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al llenar el Catálogo");
        }
    }
    
    public void AjustaColumnas()
    {
        TableColumnModel tblModeloColumnas = tblClientes.getColumnModel();
        
        tblModeloColumnas.getColumn(0).setPreferredWidth(100);
        tblModeloColumnas.getColumn(1).setPreferredWidth(250);
        tblModeloColumnas.getColumn(2).setPreferredWidth(100);     
    }
    
    public void HabilitaComponentesUsuario()
    {
        if ( uUsuario.getTipo() != 0 )
        {
            btnEliminar.setEnabled(false);
        }
        else
        {
            btnEliminar.setEnabled(true);
        }
    }
    
    public void InicializarFilas()
    {                        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //this.TotalRegistros = bdConexion.ObtenerTuplasRadiografiaCobranza(dtmTabla, getColumnas(), DameSentenciaSQL(), this.Sucursal);    
        EmpresasDescuento.DameRegistrosEmpresasDescuentos(dtmTabla, GetColumnas());
        //EscribeNumRegistros();
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    public String[] GetColumnas()
    {                        
        String strColumnas[] = new String[]{"Id"/*0*/, "Empresa"/*1*/, "Descuento"/*2*/};
        
        return strColumnas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jToolBar1 = new javax.swing.JToolBar();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta - Registros");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAgregar.setToolTipText("Agregar");
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgregar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/type_string.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gnome_edit_delete.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);
        jToolBar1.add(jSeparator2);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door_in.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSalir);

        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblClientesMouseClicked(evt);
            }
        });
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tblClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        // TODO add your handling code here:        
        AgregarEmpresa();
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void AgregarEmpresa()
    {
        FrmDetEmpresasDesctos frm = new FrmDetEmpresasDesctos(null, true);
        
        frm.show(true);
        RefrescarForma();
    }
    
    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tblClientesKeyPressed
    {//GEN-HEADEREND:event_tblClientesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblClientesKeyPressed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblClientesMouseClicked
    {//GEN-HEADEREND:event_tblClientesMouseClicked
        // TODO add your handling code here:
        if ( evt.getClickCount() == 2 )
        {
            EditaEmpresaDescuento();
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEditarActionPerformed
    {//GEN-HEADEREND:event_btnEditarActionPerformed
        // TODO add your handling code here:
        EditaEmpresaDescuento();
    }//GEN-LAST:event_btnEditarActionPerformed

    public void EditaEmpresaDescuento()
    {
        int iIDEmpresaAux = 0;
        FrmDetEmpresasDesctos frm = null;        
        
        try
        {
            if ( tblClientes != null )
            {    
                iIDEmpresaAux = Integer.parseInt(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString());
                frm = new FrmDetEmpresasDesctos(null, true, iIDEmpresaAux);        
                frm.show(true);
                RefrescarForma();            
            }
        }
        catch ( Exception e )
        {
            
        }
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarActionPerformed
    {//GEN-HEADEREND:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        EliminaEmpresaDescuento();
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    public void EliminaEmpresaDescuento()
    {
        int iID = 0;
        String strNombreEmpresa = null;
        
        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Deseas realmente eliminar la Empresa seleccionada?") == 0 )
        {
            if ( tblClientes != null )
            {    
                iID = Integer.parseInt(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString());
                strNombreEmpresa = tblClientes.getValueAt(tblClientes.getSelectedRow(), 1).toString();
                EmpresasDescuento.setID(iID);
                
                if ( EmpresasDescuento.Eliminar() )
                {
                    uAccesibilidad.MuestraMensaje("Huesped eliminado correctamente.");
                    uBitacora.InsertarAccion(uUsuario.getID(), "EL USUARIO: " + uUsuario.getNomUsuario() + " ELIMINÓ EMPRESA: " +  strNombreEmpresa, "CONSULTA DE EMPRESAS", Bitacora.ELIMINAR_EMPRESADESCTO);
                    RefrescarForma();
                }
                else
                {
                    uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de eliminar al Huesped.");
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
