/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Controlador.FormatoTabla;
import Controlador.ReportManager;
import Modelo.CorteCaja;
import Modelo.Hospedaje;
import Modelo.TablaModelo;
import Modelo.Utilerias;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JTable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Usuario
 */
public class CnsHospedajes extends javax.swing.JInternalFrame
{
    private Hospedaje Registro;
    private Utilerias uAccesibilidad;
    private TablaModelo dtmTabla;
    private CorteCaja cCorteCaja = CorteCaja.ObtenInstancia();
    /**
     * Creates new form CnsClientes
     */
    public CnsHospedajes()
    {
        initComponents();        
        Registro = new Hospedaje();
        uAccesibilidad = new Utilerias();        
        RefrescarForma(0);
    }

    public void RefrescarForma(int iOpcion)
    {
        try
        {                                  
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));  
            tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tblClientes.doLayout();                        
            dtmTabla = new TablaModelo(null, GetColumnas());               
            tblClientes.setDefaultRenderer(Object.class, new FormatoTabla());            
            InicializarFilas(iOpcion);            
            tblClientes.setModel(dtmTabla);            
            tblClientes.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
            AjustaColumnas();         
            this.setCursor(Cursor.getDefaultCursor());
            tblClientes.changeSelection(0, 1, false, false);
        }
        catch ( Exception e )
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al llenar el Catálogo");
        }
    }
    
    public void AjustaColumnas()
    {
        TableColumnModel tblModeloColumnas = tblClientes.getColumnModel();
        
        tblModeloColumnas.getColumn(0).setPreferredWidth(100);
        tblModeloColumnas.getColumn(1).setPreferredWidth(250);
        tblModeloColumnas.getColumn(2).setPreferredWidth(85);        
        tblModeloColumnas.getColumn(3).setPreferredWidth(100);
        tblModeloColumnas.getColumn(4).setPreferredWidth(80);
        tblModeloColumnas.getColumn(5).setPreferredWidth(100);
        tblModeloColumnas.getColumn(6).setPreferredWidth(100);                
        tblModeloColumnas.getColumn(7).setPreferredWidth(100);                
        tblModeloColumnas.getColumn(8).setPreferredWidth(100);        
        tblModeloColumnas.getColumn(9).setPreferredWidth(100);                
        tblModeloColumnas.getColumn(10).setPreferredWidth(300);                
    }
    
    public void InicializarFilas(int iOpcion)
    {                        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        switch ( iOpcion )
        {
            case 0: //Cuando se abre por defecto la ventana.
                Registro.DameRegistrosCnsHospedajes(dtmTabla, GetColumnas());
            break;
            case 1: //Filtro del botón 
                
            break;
            case 2: //Día de Hoy.
                Registro.DameRegistrosCnsHospedajesHoy(dtmTabla, GetColumnas());
            break;
        }
        
        //EscribeNumRegistros();
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    public String[] GetColumnas()
    {                
        //SELECT H.ID, CONCAT(C.NOMBRE, ' ', C.AP_PATERNO, ' ', C.AP_MATERNO) AS NOMBRE, H.HABITACION, H.DIAS, H.F_ENTRADA, H.F_SALIDA, H.OBSERVACIONES, H.ESTADO FROM HOSPEDAJES H LEFT JOIN HUESPEDES C ON H.HUESPED = C.ID
        String strColumnas[] = new String[]{"Id"/*0*/, "Huésped"/*1*/, "Habitación"/*2*/, "Estado" /*3*/,"Días"/*4*/, "Fecha de Entrada"/*5*/, "Fecha de Salida"/*6*/, "Total Habitación" /*7*/, "Pago completo"/*8*/, "Abono" /*9*/, "Observaciones"/*10*/};
        
        return strColumnas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jToolBar1 = new javax.swing.JToolBar();
        btnReporte1 = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnReporte2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnFiltrar = new javax.swing.JButton();
        btnFiltrarHoy = new javax.swing.JButton();
        btnFiltrarHoy1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnExportarExcel = new javax.swing.JButton();
        btnExportarExcel1 = new javax.swing.JButton();
        btnExportarExcel2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta - Registros");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnReporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CorteAlDia.png"))); // NOI18N
        btnReporte1.setToolTipText("Realizar corte al día");
        btnReporte1.setFocusable(false);
        btnReporte1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReporte1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReporte1);

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReporteCorteDia.png"))); // NOI18N
        btnReporte.setToolTipText("Reporte de corte al día");
        btnReporte.setFocusable(false);
        btnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReporteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReporte);

        btnReporte2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CheckOut.png"))); // NOI18N
        btnReporte2.setToolTipText("Detalle de hospedajes del día");
        btnReporte2.setFocusable(false);
        btnReporte2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReporte2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReporte2);
        jToolBar1.add(jSeparator3);

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Filtro_32.png"))); // NOI18N
        btnFiltrar.setToolTipText("Filtrar la consutla actual");
        btnFiltrar.setFocusable(false);
        btnFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiltrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFiltrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFiltrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFiltrar);

        btnFiltrarHoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hoy_32.png"))); // NOI18N
        btnFiltrarHoy.setToolTipText("Registros del día de HOY");
        btnFiltrarHoy.setFocusable(false);
        btnFiltrarHoy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiltrarHoy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFiltrarHoy.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFiltrarHoyActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFiltrarHoy);

        btnFiltrarHoy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Refrescar_32.png"))); // NOI18N
        btnFiltrarHoy1.setToolTipText("Restaurar Consulta");
        btnFiltrarHoy1.setFocusable(false);
        btnFiltrarHoy1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiltrarHoy1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFiltrarHoy1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFiltrarHoy1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFiltrarHoy1);
        jToolBar1.add(jSeparator2);

        btnExportarExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Excel_32.png"))); // NOI18N
        btnExportarExcel.setToolTipText("Exportar a Excel la consulta actual");
        btnExportarExcel.setFocusable(false);
        btnExportarExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportarExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExportarExcelActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExportarExcel);

        btnExportarExcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imprimir_32.png"))); // NOI18N
        btnExportarExcel1.setToolTipText("Imprimir consulta actual");
        btnExportarExcel1.setFocusable(false);
        btnExportarExcel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportarExcel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportarExcel1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExportarExcel1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExportarExcel1);

        btnExportarExcel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Calculadora.png"))); // NOI18N
        btnExportarExcel2.setToolTipText("Lanzar calculadora");
        btnExportarExcel2.setFocusable(false);
        btnExportarExcel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportarExcel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportarExcel2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExportarExcel2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExportarExcel2);
        jToolBar1.add(jSeparator1);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door_in.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tblClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1182, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tblClientesKeyPressed
    {//GEN-HEADEREND:event_tblClientesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblClientesKeyPressed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReporteActionPerformed
    {//GEN-HEADEREND:event_btnReporteActionPerformed
        // TODO add your handling code here:                        
        MuestraReporteCorteAlDiaTotales();
    }//GEN-LAST:event_btnReporteActionPerformed

    public void MuestraReporteCorteAlDiaTotales()
    {
        try
        {
            ReportManager rmReporte = new ReportManager();
                       
            rmReporte.GeneraReporteCorteAlDiaTotales();
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
    }
    
    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFiltrarActionPerformed
    {//GEN-HEADEREND:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        MostrarFiltro();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnFiltrarHoyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFiltrarHoyActionPerformed
    {//GEN-HEADEREND:event_btnFiltrarHoyActionPerformed
        // TODO add your handling code here:
        GenerarFiltroHoy();
    }//GEN-LAST:event_btnFiltrarHoyActionPerformed

    public void GenerarFiltroHoy()
    {
        RefrescarForma(2);
    }
    
    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExportarExcelActionPerformed
    {//GEN-HEADEREND:event_btnExportarExcelActionPerformed
        // TODO add your handling code here:
        ExportaConsultaExcel();
    }//GEN-LAST:event_btnExportarExcelActionPerformed

    public void ExportaConsultaExcel()
    {
        TableModel mModelo = null;       
        File fFicheroXLS = null;
        FileOutputStream fosArchivoSalida = null;
                        
        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Deseas exportar a Excel el contenido de la Tabla?") == 0 )
        {
            try
            {               
                fFicheroXLS = new File("C:/HOTEL/Reportes/ConsultaHospedajes.xls");
                fosArchivoSalida = new FileOutputStream(fFicheroXLS);
                mModelo = tblClientes.getModel();
                FileWriter fwFichero = new FileWriter(fFicheroXLS);

                for ( int j = 0; j < mModelo.getColumnCount(); j++ )
                {
                    fwFichero.write(GetColumnas()[j].toString() + "\t");
                }
                
                fwFichero.write("\n");

                for ( int i = 1; i < mModelo.getRowCount(); i++ )
                {
                    for ( int j = 0; j < mModelo.getColumnCount(); j++ )
                    {
                        try
                        {
                            if ( !mModelo.getValueAt(i, j).toString().isEmpty() )
                            {
                                fwFichero.write(mModelo.getValueAt(i, j).toString() + "\t");
                            }
                            else
                            {
                                javax.swing.JOptionPane.showMessageDialog(null, "Vacío: " + mModelo.getValueAt(i, j).toString());
                            }
                        }
                        catch ( IOException ex )
                        {
                            Logger.getLogger(CnsHospedajes.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                    fwFichero.write("\n");
                }

                fwFichero.close();
                fosArchivoSalida.close();                
                Desktop.getDesktop().open(fFicheroXLS);                
            }
            catch ( Exception e )
            {
                String strMensaje = null;
                
                strMensaje = e.getMessage();                
            }            
        }
    }
    
    public void ImprimirConsulta()
    {      
        try
        {     
            if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Desea imprimir toda la Tabla?. No se pueden seleccionar el número de impresiones") == 0 )            
            {
                tblClientes.print();
            }
        }
        catch ( PrinterException ex )
        {
            uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de Imprimir la Consulta.");          
        } 
    }
    
    private void btnFiltrarHoy1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFiltrarHoy1ActionPerformed
    {//GEN-HEADEREND:event_btnFiltrarHoy1ActionPerformed
        // TODO add your handling code here:
        RefrescarForma(0);
    }//GEN-LAST:event_btnFiltrarHoy1ActionPerformed

    private void btnExportarExcel1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExportarExcel1ActionPerformed
    {//GEN-HEADEREND:event_btnExportarExcel1ActionPerformed
        // TODO add your handling code here:
        ImprimirConsulta();
    }//GEN-LAST:event_btnExportarExcel1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirActionPerformed
    {//GEN-HEADEREND:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReporte1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReporte1ActionPerformed
    {//GEN-HEADEREND:event_btnReporte1ActionPerformed
        // TODO add your handling code here:
        GeneraCorteAlDia();
    }//GEN-LAST:event_btnReporte1ActionPerformed

    private void btnExportarExcel2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExportarExcel2ActionPerformed
    {//GEN-HEADEREND:event_btnExportarExcel2ActionPerformed
        // TODO add your handling code here:
        LanzaCalculadora();
    }//GEN-LAST:event_btnExportarExcel2ActionPerformed

    private void btnReporte2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReporte2ActionPerformed
    {//GEN-HEADEREND:event_btnReporte2ActionPerformed
        // TODO add your handling code here:
        MuestraReporteCorteDetHospedajes();
    }//GEN-LAST:event_btnReporte2ActionPerformed

    public void MuestraReporteCorteDetHospedajes()
    {
        try
        {
            ReportManager rmReporte = new ReportManager();
                       
            rmReporte.GeneraReporteCorteDetHospedajes();
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
    }
    
    public void GeneraCorteAlDia()
    {
        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Deseas generar el corte de este día?.\nAl generar el corte al día el Sistema se cerrará por seguridad.") == 0 )
        {
            if ( cCorteCaja.GeneraCorteAlDia() )
            {
                uAccesibilidad.MuestraMensaje("Corte del día generado correctamente.");
                RefrescarForma(0);
                System.exit(0);
            }
            else
            {
                uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de realizar el Corte del Día.");
            }
        }
    }
    
    public void LanzaCalculadora()
    {
        try
        {         
            Runtime rt = Runtime.getRuntime();           
            Process p = rt.exec("calc");            
            p.waitFor();    
        }
        catch (Exception e)
        {
        }
    }
    
    public void MostrarFiltro()
    {
        FrmDlgFiltroCorteAlDia frm = new FrmDlgFiltroCorteAlDia(null, true);
        
        frm.show();
    }
    
    public void LiberaHabitacion()
    {
        int iIdRegistro = 0;        
        String strEstado = null;
        String strHabitacion = null;
        
        if ( tblClientes != null )
        {        
            strEstado = tblClientes.getValueAt(tblClientes.getSelectedRow(), 3).toString();
            
            if ( strEstado.compareTo("OCUPADO") == 0 )
            {
                strHabitacion = tblClientes.getValueAt(tblClientes.getSelectedRow(), 2).toString();
                
                if ( uAccesibilidad.MuestraMensajeConfirmacion("Deseas registrar la salida de la Habitación: " + strHabitacion) == 0 )
                {
                    iIdRegistro = Integer.parseInt(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString());
                    
                    if ( Registro.LiberaHospedaje(iIdRegistro, Integer.parseInt(strHabitacion)) )
                    {
                        uAccesibilidad.MuestraMensaje("La Habitación:" + strHabitacion + " se encuentra disponible.");
                        //RefrescarForma();
                        uAccesibilidad.RepintaFormasEnMenu(this.getParent());                        
                    }
                }                
            }
        }
    }        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnExportarExcel1;
    private javax.swing.JButton btnExportarExcel2;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnFiltrarHoy;
    private javax.swing.JButton btnFiltrarHoy1;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnReporte1;
    private javax.swing.JButton btnReporte2;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
