/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Controlador.FormatoTabla;
import Modelo.Bitacora;
import Modelo.Habitacion;
import Modelo.TablaModelo;
import Modelo.Usuario;
import Modelo.Utilerias;
import java.awt.Cursor;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Usuario
 */
public class CnsHabitacionesConf extends javax.swing.JInternalFrame
{    
    //private DefaultTableModel dtmTabla;
    private TablaModelo dtmTabla;
    private Utilerias uAccesibilidad = null;
    private Habitacion hHabitacion = null;
    private Usuario uUsuario = Usuario.ObtenInstancia();
    private Bitacora uBitacora = Bitacora.ObtenInstancia();
    /**
     * Creates new form CnsClientes
     */
    public CnsHabitacionesConf()
    {
        initComponents();
        hHabitacion = new Habitacion();
        uAccesibilidad = new Utilerias();        
        RefrescarForma();     
    }
    
    public void RefrescarForma()
    {
        try
        {                      
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));  
            tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tblClientes.doLayout();                                    
            dtmTabla = new TablaModelo(null, GetColumnas());
            tblClientes.setDefaultRenderer (Object.class, new FormatoTabla() );
            InicializarFilas();            
            tblClientes.setModel(dtmTabla);
            AjustaColumnas();         
            this.setCursor(Cursor.getDefaultCursor());
            tblClientes.changeSelection(0, 1, false, false);
        }
        catch ( Exception e )
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al llenar el Catálogo");
        }
    }
    
    public void AjustaColumnas()
    {
        TableColumnModel tblModeloColumnas = tblClientes.getColumnModel();
        
        tblModeloColumnas.getColumn(0).setPreferredWidth(90);
        tblModeloColumnas.getColumn(1).setPreferredWidth(300);
        tblModeloColumnas.getColumn(2).setPreferredWidth(250);        
        tblModeloColumnas.getColumn(3).setPreferredWidth(90);
        tblModeloColumnas.getColumn(4).setPreferredWidth(90);                
    }
    
    public void InicializarFilas()
    {                        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));        
        hHabitacion.DameRegistrosCnsHabitaciones(dtmTabla, GetColumnas());
        //EscribeNumRegistros();
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    public String[] GetColumnas()
    {                
        String strColumnas[] = new String[]{"Id"/*0*/, "Tipo Habitación"/*1*/, "Descripción"/*2*/, "Precio por día"/*3*/, "Estado"/*4*/};
        
        return strColumnas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jToolBar1 = new javax.swing.JToolBar();
        btnEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta - Habitaciones");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/type_string.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);
        jToolBar1.add(jSeparator1);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door_in.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void AgregarUsuario()
    {
        FrmDetalleRecepcionista frm = null;
        
        frm = new FrmDetalleRecepcionista(null, true);
        frm.show();
        RefrescarForma();
    }
    
    public void LlenaFormaEdicionHabitacion(int iID)
    {
        FrmDetalleHabitacionD frm = null;
        
        frm = new FrmDetalleHabitacionD(null, true, iID);
        frm.show();
        RefrescarForma();
    }
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        EditaHabitacion();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblClientesMouseClicked
    {//GEN-HEADEREND:event_tblClientesMouseClicked
        // TODO add your handling code here:
        if ( evt.getClickCount() == 2 )
        {
            EditaHabitacion();
        }
    }//GEN-LAST:event_tblClientesMouseClicked
   
    
    public void Salir()
    {
        this.dispose();
    }
    
    public void EditaHabitacion()
    {
        int iID = 0;
        
        if ( tblClientes != null )
        {    
            iID = Integer.parseInt(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString());
            LlenaFormaEdicionHabitacion(iID);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
