/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Controlador.FormatoTabla;
import Modelo.SalaConferencias;
import Modelo.TablaModelo;
import Modelo.Utilerias;
import java.awt.Cursor;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Usuario
 */
public class CnsReservacionesSalaConf extends javax.swing.JDialog
{
    private TablaModelo dtmTabla;
    private Utilerias uAccesibilidad = null;    
    private SalaConferencias scSala = null;
    /**
     * Creates new form NewJDialog
     */
    public CnsReservacionesSalaConf(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        uAccesibilidad = new Utilerias();
        scSala = new SalaConferencias();
        RefrescarForma();
    }

    public void RefrescarForma()
    {
        try
        {                      
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));  
            tblReservaciones.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tblReservaciones.doLayout();                                    
            tblReservaciones.setRowHeight(50);
            tblReservaciones.setShowHorizontalLines(true);
            tblReservaciones.setShowVerticalLines(true);
            dtmTabla = new TablaModelo(null, GetColumnas());
            tblReservaciones.setDefaultRenderer (Object.class, new FormatoTabla() );
            InicializarFilas();            
            tblReservaciones.setModel(dtmTabla);
            AjustaColumnas();         
            this.setCursor(Cursor.getDefaultCursor());
        }
        catch ( Exception e )
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al llenar el Catálogo");
        }
    }
    
    public void AjustaColumnas()
    {
        TableColumnModel tblModeloColumnas = tblReservaciones.getColumnModel();
                
        tblModeloColumnas.getColumn(0).setPreferredWidth(50);
        tblModeloColumnas.getColumn(1).setPreferredWidth(200);
        tblModeloColumnas.getColumn(2).setPreferredWidth(180);        
        tblModeloColumnas.getColumn(3).setPreferredWidth(180);        
        tblModeloColumnas.getColumn(4).setPreferredWidth(180);        
    }
    
    public void InicializarFilas()
    {                        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));           
        scSala.DameRegistrosReservados(dtmTabla, GetColumnas());
        //EscribeNumRegistros();
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    public String[] GetColumnas()
    {                
        String strColumnas[] = new String[]{"Id"/*0*/, "Nombre"/*1*/, "Fecha"/*2*/, "Inicia"/*3*/, "Termina"/*4*/};
        
        return strColumnas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblReservaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        tblReservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblReservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblReservaciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblReservaciones.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblReservacionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblReservaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblReservacionesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblReservacionesMouseClicked
    {//GEN-HEADEREND:event_tblReservacionesMouseClicked
        // TODO add your handling code here:
        if ( evt.getClickCount() == 2 )
        {
            //EditaUsuario();
        }
    }//GEN-LAST:event_tblReservacionesMouseClicked

    public void Prueba()
    {
       // jcCalendario.set
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CnsReservacionesSalaConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CnsReservacionesSalaConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CnsReservacionesSalaConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CnsReservacionesSalaConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                CnsReservacionesSalaConf dialog = new CnsReservacionesSalaConf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblReservaciones;
    // End of variables declaration//GEN-END:variables
}
