/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Modelo.Bitacora;
import Modelo.Descuento;
import Modelo.Huesped;
import Modelo.Usuario;
import Modelo.Utilerias;

/**
 *
 * @author WIN7UTL64
 */
public class FrmDetCliente extends javax.swing.JDialog 
{
    Huesped hCliente = null;
    private Utilerias uAccesibilidad;    
    private boolean Agregar = true;
    private boolean RequiereFactura = false;
    private Usuario uUsuario = Usuario.ObtenInstancia();
    private Bitacora uBitacora = Bitacora.ObtenInstancia();
    /**
     * Creates new form FrmDetCliente
     */
    public FrmDetCliente(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        hCliente = new Huesped();
        uAccesibilidad = new Utilerias();
        this.Agregar = true;
        MuestraOcultaPanelFiscales();
    }
    
    public FrmDetCliente(java.awt.Frame parent, boolean modal, int iID) 
    {
        super(parent, modal);
        initComponents();
        hCliente = new Huesped();
        hCliente.InstanciaHuesped(iID);
        uAccesibilidad = new Utilerias();    
        LlenaForma();
        this.Agregar = false;
        this.RequiereFactura = ( hCliente.getRequiereFactura() == 1 );
        MuestraOcultaPanelFiscales();
    }
    
    public void LlenaForma()
    {
        Descuento dDescuento = new Descuento();
        
        txtNombre.setText(hCliente.getNombre());
        txtApPaterno.setText(hCliente.getApPaterno());
        txtApMaterno.setText(hCliente.getApMaterno());
        txtRfc.setText(hCliente.getRfc());
        txtDireccion.setText(hCliente.getDireccion());
        txtTelefono.setText(hCliente.getTelefono());
        txtPais.setText(hCliente.getPais());
        cmboxProcedencia.setSelectedIndex(hCliente.getProcedencia() == 0 ? 0 : 1);
        txtEmail.setText(hCliente.getEmail());
        cboxDescuentoEmpresas.setSelected(hCliente.getAplicaDescuento() == 1 ? true : false);
        cboxRequiereFactura.setSelected(hCliente.getRequiereFactura() == 1 ? true : false);        
        dDescuento.InstanciaEmpresaDescuentos(hCliente.getEmpresa());
        txtEmpresa.setText(dDescuento.getEmpresa());
        txtEmail.setText(hCliente.getEmail());
        txtCalle.setText(hCliente.getCalle());
        txtNumExt.setText(hCliente.getNumExt());
        txtNumInt.setText(hCliente.getNumInt());
        txtColonia.setText(hCliente.getColonia());
        txtPoblacion.setText(hCliente.getPoblacion());
        txtMunicipio.setText(hCliente.getMunicipio());
        txtEstado.setText(hCliente.getEstado());
        txtCP.setText(hCliente.getCP());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        Pestanias = new javax.swing.JTabbedPane();
        PanelCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmboxProcedencia = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        PanelEmpresasDescuento = new javax.swing.JPanel();
        labelNombreEmpresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        btnEmpresas = new javax.swing.JButton();
        cboxDescuentoEmpresas = new javax.swing.JCheckBox();
        cboxRequiereFactura = new javax.swing.JCheckBox();
        PanelFiscales = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNumExt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        txtNumInt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle de Huespedes");

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Agregar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpiarCampos.setText("Limpiar");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        PanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Húesped"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Apellido Paterno");
        jLabel2.setToolTipText("");

        txtApPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtApPaternoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Apellido Materno");

        txtApMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtApMaternoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("RFC");

        txtRfc.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtRfcKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Dirección");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Teléfono");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("País");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Procedencia");

        cmboxProcedencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nacional", "Extranjero" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Email");

        PanelEmpresasDescuento.setBorder(javax.swing.BorderFactory.createTitledBorder("Descuento a empresas"));
        PanelEmpresasDescuento.setEnabled(false);

        labelNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNombreEmpresa.setText("Empresa:");
        labelNombreEmpresa.setEnabled(false);

        txtEmpresa.setEnabled(false);

        btnEmpresas.setText("...");
        btnEmpresas.setEnabled(false);
        btnEmpresas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEmpresasDescuentoLayout = new javax.swing.GroupLayout(PanelEmpresasDescuento);
        PanelEmpresasDescuento.setLayout(PanelEmpresasDescuentoLayout);
        PanelEmpresasDescuentoLayout.setHorizontalGroup(
            PanelEmpresasDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmpresasDescuentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpresas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEmpresasDescuentoLayout.setVerticalGroup(
            PanelEmpresasDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmpresasDescuentoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelEmpresasDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreEmpresa)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpresas))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cboxDescuentoEmpresas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxDescuentoEmpresas.setText("Aplica descuento a empresa");
        cboxDescuentoEmpresas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cboxDescuentoEmpresasActionPerformed(evt);
            }
        });

        cboxRequiereFactura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxRequiereFactura.setText("Requiere factura");
        cboxRequiereFactura.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cboxRequiereFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelClienteLayout = new javax.swing.GroupLayout(PanelCliente);
        PanelCliente.setLayout(PanelClienteLayout);
        PanelClienteLayout.setHorizontalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtRfc)
                    .addComponent(txtTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelClienteLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPais))
                        .addGap(70, 70, 70)
                        .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cmboxProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDireccion)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelClienteLayout.createSequentialGroup()
                                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(PanelEmpresasDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelClienteLayout.createSequentialGroup()
                            .addComponent(cboxDescuentoEmpresas)
                            .addGap(27, 27, 27)
                            .addComponent(cboxRequiereFactura))))
                .addGap(0, 91, Short.MAX_VALUE))
        );
        PanelClienteLayout.setVerticalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelClienteLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelClienteLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmboxProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxDescuentoEmpresas)
                    .addComponent(cboxRequiereFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelEmpresasDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Pestanias.addTab("Húesped", PanelCliente);

        PanelFiscales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Fiscales"));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Calle:");

        txtCalle.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtCalleKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Num Ext:");

        txtNumExt.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNumExtKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Num Int:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Colonia:");

        txtColonia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtColoniaKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Población:");

        txtPoblacion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtPoblacionKeyTyped(evt);
            }
        });

        txtMunicipio.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtMunicipioKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Municipio:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Estado:");

        txtEstado.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtEstadoKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("CP:");

        txtCP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtCPKeyTyped(evt);
            }
        });

        txtNumInt.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNumIntKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PanelFiscalesLayout = new javax.swing.GroupLayout(PanelFiscales);
        PanelFiscales.setLayout(PanelFiscalesLayout);
        PanelFiscalesLayout.setHorizontalGroup(
            PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiscalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFiscalesLayout.createSequentialGroup()
                        .addComponent(txtNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumInt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFiscalesLayout.createSequentialGroup()
                        .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(292, 292, 292))
        );

        PanelFiscalesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCalle, txtColonia, txtEstado, txtMunicipio, txtPoblacion});

        PanelFiscalesLayout.setVerticalGroup(
            PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiscalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNumInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFiscalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        Pestanias.addTab("Fiscales", PanelFiscales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiarCampos))
                    .addComponent(Pestanias, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pestanias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar)
                    .addComponent(btnLimpiarCampos))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        uAccesibilidad.RestringirCaracteres(txtNombre, evt, 50);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPaternoKeyTyped
        // TODO add your handling code here:
        uAccesibilidad.RestringirCaracteres(txtApPaterno, evt, 50);
    }//GEN-LAST:event_txtApPaternoKeyTyped

    private void txtApMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMaternoKeyTyped
        // TODO add your handling code here:
        uAccesibilidad.RestringirCaracteres(txtApMaterno, evt, 45);
    }//GEN-LAST:event_txtApMaternoKeyTyped

    private void txtRfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcKeyTyped
        // TODO add your handling code here:
        uAccesibilidad.RestringirCaracteres(txtRfc, evt, 20);
    }//GEN-LAST:event_txtRfcKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        AgregarCliente();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasActionPerformed
        // TODO add your handling code here:
        MuestraListaEmpresasDescuentos();
    }//GEN-LAST:event_btnEmpresasActionPerformed

    private void cboxDescuentoEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDescuentoEmpresasActionPerformed
        // TODO add your handling code here:
        hCliente.setAplicaDescuento(cboxDescuentoEmpresas.isSelected() ? 1 : 0);
        HabilitaDeshEmpresa(cboxDescuentoEmpresas.isSelected());
    }//GEN-LAST:event_cboxDescuentoEmpresasActionPerformed

    private void cboxRequiereFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRequiereFacturaActionPerformed
        // TODO add your handling code here:
        RequiereFactura = cboxRequiereFactura.isSelected();
        hCliente.setRequiereFactura(RequiereFactura ? 1 : 0);
        MuestraOcultaPanelFiscales();
    }//GEN-LAST:event_cboxRequiereFacturaActionPerformed

    public void MuestraOcultaPanelFiscales()
    {
        if ( RequiereFactura )
        {            
            if ( Pestanias.getTabCount() == 1 )
            {
                Pestanias.addTab("Fiscales", PanelFiscales);
            }
        }
        else
        {
            Pestanias.remove(PanelFiscales);
        }
    }
    
    private void txtCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleKeyTyped

    private void txtNumExtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumExtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumExtKeyTyped

    private void txtColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColoniaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColoniaKeyTyped

    private void txtPoblacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoblacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoblacionKeyTyped

    private void txtMunicipioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMunicipioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunicipioKeyTyped

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPKeyTyped

    private void txtNumIntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumIntKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIntKeyTyped

    public void HabilitaDeshEmpresa(boolean bActivar)
    {
        PanelEmpresasDescuento.setEnabled(bActivar);
        labelNombreEmpresa.setEnabled(bActivar);
        btnEmpresas.setEnabled(bActivar);
    }
    
    public void MuestraListaEmpresasDescuentos()
    {
        FrmListaEmpresas frm = new FrmListaEmpresas(null, true);
        
        frm.show(true);
        this.hCliente.setEmpresa(frm.getIDEmpresa());
        txtEmpresa.setText(frm.getNombreEmpresa());        
    }
    
    public void LimpiarCampos()
    {
        txtNombre.setText(null);
        txtApPaterno.setText(null);
        txtApMaterno.setText(null);
        txtRfc.setText(null);
        txtDireccion.setText(null);
        txtTelefono.setText(null);
        txtPais.setText(null);
        cmboxProcedencia.setSelectedIndex(0);
        txtEmail.setText(null);
        cboxDescuentoEmpresas.setSelected(false);
        cboxRequiereFactura.setSelected(false);
        txtEmpresa.setText(null);
        txtCalle.setText(null);
        txtNumExt.setText(null);
        txtNumInt.setText(null);
        txtColonia.setText(null);
        txtPoblacion.setText(null);
        txtMunicipio.setText(null);
        txtEstado.setText(null);
        txtCP.setText(null);
    }
    
    public void AgregarCliente()
    {      
        String strNombre = null;
        
        if ( HuespedValido() )
        {
            strNombre = txtNombre.getText() + " " + txtApPaterno.getText() + " " + txtApMaterno.getText();
            hCliente.setNombre(txtNombre.getText());
            hCliente.setApPaterno(txtApPaterno.getText());
            hCliente.setApMaterno(txtApMaterno.getText());
            hCliente.setRfc(txtRfc.getText());
            hCliente.setDireccion(txtDireccion.getText());
            hCliente.setTelefono(txtTelefono.getText());
            hCliente.setPais(txtPais.getText());
            hCliente.setProcedencia(cmboxProcedencia.getSelectedIndex());
            hCliente.setEmail(txtEmail.getText());
            hCliente.setCalle(txtCalle.getText());
            hCliente.setNumExt(txtNumExt.getText());
            hCliente.setNumInt(txtNumInt.getText());
            hCliente.setColonia(txtColonia.getText());
            hCliente.setPoblacion(txtPoblacion.getText());
            hCliente.setMunicipio(txtMunicipio.getText());
            hCliente.setEstado(txtEstado.getText());
            hCliente.setCP(txtCP.getText());
            
            if ( this.Agregar )
            {
                if ( hCliente.Insertar() )
                {                
                    uAccesibilidad.MuestraMensaje("Huesped agregado correctamente");
                    uBitacora.InsertarAccion(uUsuario.getID(), "EL USUARIO: " + uUsuario.getNomUsuario() + " AGREGÓ HUESPED: " + strNombre, "DETALLE DE HUESPEDES", Bitacora.AGREGAR_CLIENTE);
                    LimpiarCampos();
                }
            }
            else
            {
                if ( hCliente.Actualizar() )
                {                
                    uAccesibilidad.MuestraMensaje("Datos actualizados correctamente.");
                    uBitacora.InsertarAccion(uUsuario.getID(), "EL USUARIO: " + uUsuario.getNomUsuario() + " EDITÓ HUESPED: " + strNombre , "DETALLE DE HUESPEDES", Bitacora.EDITAR_CLIENTE);
                    this.dispose();
                }
            }
        }
        else
        {
            MuestraMensajeCampoVacio();
        }
    }
    
    public void MuestraMensajeCampoVacio()
    {
        String strMensaje = "";
        
        if ( txtNombre.getText().isEmpty() )
        {
            strMensaje = "Nombre";
        }
        else if ( txtApPaterno.getText().isEmpty() )
        {
            strMensaje = "Apellido Paterno";    
        }
        else if ( txtPais.getText().isEmpty() )
        {
            strMensaje = "País";   
        }
        
        if ( RequiereFactura )
        {
            if ( txtCalle.getText().isEmpty() )
            {
                strMensaje = "Calle";
            }
            else if ( txtNumExt.getText().isEmpty() )
            {
                strMensaje = "Número Exterior";
            }
            else if ( txtColonia.getText().isEmpty() )
            {
                strMensaje = "Colonia";
            }
            else if ( txtPoblacion.getText().isEmpty() )
            {
                strMensaje = "Población";
            }
            else if ( txtMunicipio.getText().isEmpty() )
            {
                strMensaje = "Municipio";
            }
            else if ( txtEstado.getText().isEmpty() )
            {
                strMensaje = "Estado";
            }
            else if ( txtCP.getText().isEmpty() )
            {
                strMensaje = "Código Postal";
            }
        }
        
        uAccesibilidad.MuestraMensaje("El campo " + strMensaje + " no puede ser vacío");
        
        if ( txtNombre.getText().isEmpty() )
        {
            txtNombre.requestFocus();
            txtNombre.selectAll();
        }
        else if ( txtApPaterno.getText().isEmpty() )
        {
            txtApPaterno.requestFocus();
            txtApPaterno.selectAll();
        }
        else if ( txtPais.getText().isEmpty() )
        {
            txtPais.requestFocus();
            txtPais.selectAll();
        }
        
        if ( RequiereFactura )
        {
            if ( txtCalle.getText().isEmpty() )
            {
                txtCalle.requestFocus();
                txtCalle.selectAll();
            }
            else if ( txtNumExt.getText().isEmpty() )
            {
                txtNumExt.requestFocus();
                txtNumExt.selectAll();
            }
            else if ( txtColonia.getText().isEmpty() )
            {
                txtColonia.requestFocus();
                txtColonia.selectAll();
            }
            else if ( txtPoblacion.getText().isEmpty() )
            {
                txtPoblacion.requestFocus();
                txtPoblacion.selectAll();
            }
            else if ( txtMunicipio.getText().isEmpty() )
            {
                txtMunicipio.requestFocus();
                txtMunicipio.selectAll();
            }
            else if ( txtEstado.getText().isEmpty() )
            {
                txtEstado.requestFocus();
                txtEstado.selectAll();
            }
            else if ( txtCP.getText().isEmpty() )
            {
                txtCP.requestFocus();
                txtCP.selectAll();
            }
        }
    }
    
    public boolean HuespedValido()
    {
        boolean bOk = true;
                
        if ( txtNombre.getText().isEmpty() || txtApPaterno.getText().isEmpty() || txtPais.getText().isEmpty())
        {
            bOk = false;
        }
        
        if ( RequiereFactura )
        {
            if ( txtCalle.getText().isEmpty() || txtColonia.getText().isEmpty() || txtPoblacion.getText().isEmpty() || 
                 txtMunicipio.getText().isEmpty() || txtEstado.getText().isEmpty() || txtCP.getText().isEmpty() )
            {
                bOk = false;
            }
        }
        
        return bOk;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDetCliente dialog = new FrmDetCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JPanel PanelEmpresasDescuento;
    private javax.swing.JPanel PanelFiscales;
    private javax.swing.JTabbedPane Pestanias;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEmpresas;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JCheckBox cboxDescuentoEmpresas;
    private javax.swing.JCheckBox cboxRequiereFactura;
    private javax.swing.JComboBox cmboxProcedencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelNombreEmpresa;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumExt;
    private javax.swing.JTextField txtNumInt;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPoblacion;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
