/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Modelo.Habitacion;
import Modelo.Huesped;
import Modelo.Reservacion;
import Modelo.Utilerias;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author LCC Luis Alberto Flores Castillo <luis.ejob@gmail.com>
 */
public class FrmDlgReservarHabitacion extends javax.swing.JDialog
{
    private int IdHuesped;
    private Huesped Cliente = null;
    private Utilerias uAccesibilidad = null;  
    private Reservacion ReservacionHabitacion = null;
    /**
     * Creates new form FrmDlgReservarHabitacion
     */
    public FrmDlgReservarHabitacion(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.uAccesibilidad = new Utilerias();
        this.Cliente = new Huesped();
        this.ReservacionHabitacion = new Reservacion();
        ConfiguraLlenadoHuespedes(true);
        AsignaEventosBotonesVentana();
    }

    public void AsignaEventosBotonesVentana()
    {
        Action btnAccionPagar = new AbstractAction("ACEPTAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnAceptarActionPerformed(evt);
            }
        };        

        Action btnAccionCancelar = new AbstractAction("CERRAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnCancelarActionPerformed(evt);
            }
        };
        
        Action btnAccionListaHuespedes = new AbstractAction("LISTA") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnHuespedActionPerformed(evt);
            }
        };
         
        btnAceptar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "Pagar"); 
        btnAceptar.getActionMap().put("Pagar", btnAccionPagar);        
        btnCancelar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "Cancelar"); 
        btnCancelar.getActionMap().put("Cancelar", btnAccionCancelar); 
        btnHuesped.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "F2"); 
        btnHuesped.getActionMap().put("F2", btnAccionListaHuespedes); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbboxHabitacion = new javax.swing.JComboBox();
        labelFecha = new javax.swing.JLabel();
        dtFecha = new com.toedter.calendar.JDateChooser();
        cboxHuespedNuevo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        labelHuesped = new javax.swing.JLabel();
        txtHuesped = new javax.swing.JTextField();
        btnHuesped = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Habitación"));

        jLabel1.setDisplayedMnemonic('h');
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setLabelFor(cmbboxHabitacion);
        jLabel1.setText("Habitación:");

        cmbboxHabitacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Habitación 1", "Habitación 2", "Habitación 3", "Habitación 4", "Habitación 5", "Habitación 6", "Habitación 7", "Habitación 8", "Habitación 9", "Habitación 10", "Habitación 11", "Habitación 12", "Habitación 13", "Habitación 14", "Habitación 15", "Habitación 16", "Habitación 17", "Habitación 18", "Habitación 19", "Habitación 20", "Habitación 21", "Habitación 22", "Habitación 23", "Habitación 24", "Habitación 25", "Habitación 26", "Habitación 27", "Habitación 28" }));

        labelFecha.setDisplayedMnemonic('F');
        labelFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelFecha.setLabelFor(dtFecha);
        labelFecha.setText("Fecha:");

        cboxHuespedNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxHuespedNuevo.setMnemonic('a');
        cboxHuespedNuevo.setSelected(true);
        cboxHuespedNuevo.setText("Húesped nuevo");
        cboxHuespedNuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cboxHuespedNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbboxHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboxHuespedNuevo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFecha)
                            .addComponent(dtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbboxHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cboxHuespedNuevo))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Húesped"));
        jPanel2.setToolTipText("");

        jLabel16.setDisplayedMnemonic('N');
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setLabelFor(txtNombre);
        jLabel16.setText("* Nombre");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel17.setDisplayedMnemonic('P');
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setLabelFor(txtApPaterno);
        jLabel17.setText("* Apellido Paterno");
        jLabel17.setToolTipText("");

        txtApPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtApPaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtApPaternoKeyTyped(evt);
            }
        });

        jLabel18.setDisplayedMnemonic('m');
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setLabelFor(txtApMaterno);
        jLabel18.setText("Apellido Materno");

        txtApMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtApMaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtApMaternoKeyTyped(evt);
            }
        });

        jLabel6.setDisplayedMnemonic('t');
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setLabelFor(txtTelefono);
        jLabel6.setText("Teléfono");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtTelefonoKeyPressed(evt);
            }
        });

        labelHuesped.setDisplayedMnemonic('e');
        labelHuesped.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelHuesped.setText("Huésped");

        txtHuesped.setEnabled(false);

        btnHuesped.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHuesped.setText("[F2]");
        btnHuesped.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnHuespedActionPerformed(evt);
            }
        });

        jLabel19.setDisplayedMnemonic('P');
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setLabelFor(txtApPaterno);
        jLabel19.setText("* Únicamente se permite reservar Habitaciones disponibles");
        jLabel19.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelHuesped)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuesped)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(txtApPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(390, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHuesped)
                    .addComponent(txtHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuesped))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Reservar [F3]");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar [F4]");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyPressed
    {//GEN-HEADEREND:event_txtNombreKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtApPaterno.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyTyped
    {//GEN-HEADEREND:event_txtNombreKeyTyped
        // TODO add your handling code here:
        uAccesibilidad.RestringirCaracteres(txtNombre, evt, 50);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApPaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtApPaternoKeyPressed
    {//GEN-HEADEREND:event_txtApPaternoKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtApMaterno.requestFocus();
        }
    }//GEN-LAST:event_txtApPaternoKeyPressed

    private void txtApPaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtApPaternoKeyTyped
    {//GEN-HEADEREND:event_txtApPaternoKeyTyped
        // TODO add your handling code here:
        uAccesibilidad.RestringirCaracteres(txtApPaterno, evt, 50);
    }//GEN-LAST:event_txtApPaternoKeyTyped

    private void txtApMaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtApMaternoKeyPressed
    {//GEN-HEADEREND:event_txtApMaternoKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtTelefono.requestFocus();
        }
    }//GEN-LAST:event_txtApMaternoKeyPressed

    private void txtApMaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtApMaternoKeyTyped
    {//GEN-HEADEREND:event_txtApMaternoKeyTyped
        // TODO add your handling code here:
        uAccesibilidad.RestringirCaracteres(txtApMaterno, evt, 45);
    }//GEN-LAST:event_txtApMaternoKeyTyped

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtTelefonoKeyPressed
    {//GEN-HEADEREND:event_txtTelefonoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void btnHuespedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHuespedActionPerformed
    {//GEN-HEADEREND:event_btnHuespedActionPerformed
        // TODO add your handling code here:
        MuestraListaHuespedes();
    }//GEN-LAST:event_btnHuespedActionPerformed

    public void MuestraListaHuespedes()            
    {
        String strNombre = null;
        FrmListaHuespedes frm = new FrmListaHuespedes(null, true);
        
        frm.show();
        
        if ( frm.isPresionoAceptar() )
        {
            LimpiarCampos();
            this.IdHuesped = frm.getIdHuesped();
            strNombre = frm.getNombre() + " " + frm.getApPaterno() + " " + frm.getApMaterno();
            txtHuesped.setText(strNombre);
            txtNombre.setText(frm.getNombre());
            txtApPaterno.setText(frm.getApPaterno());
            txtApMaterno.setText(frm.getApMaterno());
            txtTelefono.setText(frm.getTelefono());
        }        
    }
    
    public void LimpiarCampos()
    {
        this.IdHuesped = 0;
        txtHuesped.setText(null);
        txtNombre.setText(null);
        txtApPaterno.setText(null);
        txtApMaterno.setText(null);
        txtTelefono.setText(null);
    }
    
    public void ConfiguraLlenadoHuespedes(boolean bHuespedNuevo)
    {                       
        labelHuesped.setEnabled(!bHuespedNuevo);
        btnHuesped.setEnabled(!bHuespedNuevo);
        txtNombre.setEnabled(bHuespedNuevo);
        txtApPaterno.setEnabled(bHuespedNuevo);
        txtApMaterno.setEnabled(bHuespedNuevo);
        txtTelefono.setEnabled(bHuespedNuevo);
    }
    
    private void cboxHuespedNuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cboxHuespedNuevoActionPerformed
    {//GEN-HEADEREND:event_cboxHuespedNuevoActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
        ConfiguraLlenadoHuespedes(cboxHuespedNuevo.isSelected());        
    }//GEN-LAST:event_cboxHuespedNuevoActionPerformed

    public boolean HabitacionValida(int iIdHabitacion)
    {
        boolean bOk = false;
        Habitacion hAux = new Habitacion();
        
        hAux.DameHabitacionInstanciada(iIdHabitacion);        
        bOk = ( hAux.getEstado() == 0 );
        
        return bOk;
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        Reservar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    public int DameHabitacion()
    {
        int iHabitacion = 0;
        
        iHabitacion = ( cmbboxHabitacion.getSelectedIndex() + 1 );
        
        return iHabitacion;
    }
    
    public void AgregaCliente()
    {
        Cliente.setNombre(txtNombre.getText());
        Cliente.setApPaterno(txtApPaterno.getText());
        Cliente.setApMaterno(txtApMaterno.getText());        
        Cliente.setTelefono(txtTelefono.getText());        
    }
    
    public boolean HuespedValido()
    {
        boolean bOk = false;
        
        if ( ( !txtNombre.getText().isEmpty() ) && ( !txtApPaterno.getText().isEmpty() ) )
        {
            bOk = true;
        }
        
        return bOk;
    }
    
    public void Reservar()
    {
        Date dtFechaActual = new Date();
        boolean bContinuar = true;
        
        if ( HuespedValido() )
        {
            if ( HabitacionValida(DameHabitacion()) )
            {
                if ( ( dtFecha.getDate() != null ) && ( dtFecha.getDate().getTime() > dtFechaActual.getTime() ) )
                {
                    if ( !ReservacionHabitacion.HabitacionReservada(DameHabitacion(), dtFecha.getDate()) )
                    {
                        if ( cboxHuespedNuevo.isSelected() )
                        {
                            AgregaCliente();
                            bContinuar = Cliente.Insertar();

                            if ( bContinuar )
                            {
                                this.IdHuesped = Cliente.getId();
                            }
                        }

                        if ( bContinuar )
                        {
                            if ( ReservacionHabitacion.Insertar(DameHabitacion(), IdHuesped, dtFecha.getDate()) )
                            {
                                uAccesibilidad.MuestraMensaje("Reservación generada correctamente.");
                                this.dispose();
                            }
                            else
                            {
                                uAccesibilidad.MuestraMensaje("Ha ocurrido un error al tratar de agregar la Reservación.");
                            }
                        }
                    }
                    else
                    {
                        uAccesibilidad.MuestraMensaje("La Habitación: " + DameHabitacion() + " ya se encuentra reservada para esa fecha.");
                    }
                }
                else
                {
                    uAccesibilidad.MuestraMensaje("No se puede dejar una fecha inválida.");
                }
            }
            else
            {
                uAccesibilidad.MuestraMensaje("La Habitación: " + DameHabitacion() + " no está disponible para ser reservada.");
            }
        }
        else
        {
            uAccesibilidad.MuestraMensaje("El Nombre y Apellido Paterno no pueden estar vacíos.");
        }        
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        // TODO add your handling code here:        
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmDlgReservarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmDlgReservarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmDlgReservarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmDlgReservarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FrmDlgReservarHabitacion dialog = new FrmDlgReservarHabitacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnHuesped;
    private javax.swing.JCheckBox cboxHuespedNuevo;
    private javax.swing.JComboBox cmbboxHabitacion;
    private com.toedter.calendar.JDateChooser dtFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHuesped;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtHuesped;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
