/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Modelo.Paquete;
import Modelo.Utilerias;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author WIN7UTL64
 */
public class FrmDetPaquete extends javax.swing.JDialog 
{
    private boolean Agregar;
    private int TipoOperacion;
    private Utilerias uAccesibilidad;
    private Paquete pPaquete;
    /**
     * Creates new form FrmDetSalaConferencias
     */
    public FrmDetPaquete(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        AsignaEventosBotonesVentana();
        this.TipoOperacion = 0;
        uAccesibilidad = new Utilerias();        
        pPaquete = new Paquete();
        LimpiaCampos();
        this.Agregar = true;
    }

    public FrmDetPaquete(java.awt.Frame parent, boolean modal, int iIdPaquete) 
    {
        super(parent, modal);
        initComponents();        
        AsignaEventosBotonesVentana();
        uAccesibilidad = new Utilerias();        
        pPaquete = new Paquete();
        pPaquete.InstanciaPaquete(iIdPaquete);
        LlenaCampos();
        this.Agregar = false;
    }
    
    public void AsignaEventosBotonesVentana()
    {
        Action btnAccionPagar = new AbstractAction("PAGAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnAceptarActionPerformed(evt);
            }
        };

        Action btnAccionLimpiar = new AbstractAction("LIMPIAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnLimpiarCamposActionPerformed(evt);
            }
        };

        Action btnAccionCancelar = new AbstractAction("CERRAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnCancelarActionPerformed(evt);
            }
        };
                        
        btnAceptar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "Aceptar"); 
        btnAceptar.getActionMap().put("Aceptar", btnAccionPagar);
        btnLimpiarCampos.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "Limpiar"); 
        btnLimpiarCampos.getActionMap().put("Limpiar", btnAccionLimpiar);
        btnCancelar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "Cancelar"); 
        btnCancelar.getActionMap().put("Cancelar", btnAccionCancelar);         
    }
    
    public void LlenaCampos()
    {
        txtDescripcion.setText(pPaquete.getDescripcion());
        txtHoras.setText(String.valueOf(pPaquete.getHoras()));
        txtPrecioSala.setText(String.valueOf(pPaquete.getPrecioSala()));
        txtCoffe.setText(String.valueOf(pPaquete.getPrecioCoffee()));
        txtAlmuerzo.setText(String.valueOf(pPaquete.getPrecioAlmuerzoPP()));
    }
    
    public void LimpiaCampos()
    {
        txtHoras.setText(null);
        txtDescripcion.setText(null);
        txtPrecioSala.setText("0.0");
        txtCoffe.setText("0.0");
        txtAlmuerzo.setText("0.0");
        txtDescripcion.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrecioSala = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCoffe = new javax.swing.JFormattedTextField();
        txtAlmuerzo = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de paquetes para Sala de conferencias");

        jLabel1.setDisplayedMnemonic('h');
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setLabelFor(txtHoras);
        jLabel1.setText("Horas:");

        txtHoras.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtHorasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtHorasKeyTyped(evt);
            }
        });

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtDescripcionKeyPressed(evt);
            }
        });

        jLabel2.setDisplayedMnemonic('s');
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setLabelFor(txtPrecioSala);
        jLabel2.setText("Precio sala:");

        txtPrecioSala.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecioSala.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtPrecioSalaFocusGained(evt);
            }
        });
        txtPrecioSala.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtPrecioSalaKeyPressed(evt);
            }
        });

        jLabel3.setDisplayedMnemonic('c');
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setLabelFor(txtCoffe);
        jLabel3.setText("Precio con Coffe Break:");

        txtCoffe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCoffe.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtCoffeFocusGained(evt);
            }
        });
        txtCoffe.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtCoffeKeyPressed(evt);
            }
        });

        txtAlmuerzo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtAlmuerzo.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtAlmuerzoFocusGained(evt);
            }
        });

        jLabel4.setDisplayedMnemonic('a');
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setLabelFor(txtAlmuerzo);
        jLabel4.setText("Precio con almuerzo:");

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Agregar (F3)");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar (F4)");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpiarCampos.setText("Limpiar (F1)");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        jLabel5.setDisplayedMnemonic('d');
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setLabelFor(txtDescripcion);
        jLabel5.setText("Descripción paquete:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiarCampos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAlmuerzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(txtCoffe, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrecioSala, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHoras, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecioSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCoffe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar)
                    .addComponent(btnLimpiarCampos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        AgregarPaquete();
    }//GEN-LAST:event_btnAceptarActionPerformed

    public void AgregarPaquete()
    {
        if ( DatosCompletos() )
        {
            this.pPaquete.setDescripcion(txtDescripcion.getText());
            this.pPaquete.setHoras(DameTotalHoras());
            this.pPaquete.setPrecioSala(DamePrecioSala());
            this.pPaquete.setPrecioCoffee(DamePrecioCoffe());
            this.pPaquete.setPrecioAlmuerzoPP(DamePrecioAlmuerzo());
            
            if ( Agregar )
            {
                if ( this.pPaquete.Insertar() )
                {
                    uAccesibilidad.MuestraMensaje("Se ha agregado un paquete correctamente.");
                }
                else
                {
                    uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de agregar un nuevo Paquete.");
                }
                
                LimpiaCampos();
            }
            else
            {
                if ( this.pPaquete.Actualizar() )
                {
                    uAccesibilidad.MuestraMensaje("Se ha actualizado correctamente el paquete.");
                }
                else
                {
                    uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de editar el Paquete.");
                }
                
                this.dispose();
            }                        
        }
        else
        {
            MuestraMensajeError();
        }
    }
    
    public void MuestraMensajeError()
    {
        if ( txtDescripcion.getText().isEmpty() )
        {
            uAccesibilidad.MuestraMensaje("La Descripción del paquete no puede estar vacía.");
            txtDescripcion.requestFocus();
            txtDescripcion.selectAll();
        }
        else if ( DameTotalHoras() <= 0 )
        {
            uAccesibilidad.MuestraMensaje("Se debe tener un total de al menos 1 hora.");
            txtHoras.requestFocus();
            txtHoras.selectAll();            
        }
        else if ( DamePrecioSala() <= 0.0 )
        {
            uAccesibilidad.MuestraMensaje("El Precio de la Sala debe ser mayor a 0.");
            txtPrecioSala.requestFocus();
            txtPrecioSala.selectAll();
        }
        else if ( DamePrecioCoffe() <= 0.0 )
        {
            uAccesibilidad.MuestraMensaje("El Precio con Coffe Break debe ser mayor a 0.");
            txtCoffe.requestFocus();
            txtCoffe.selectAll();
        }
        else if ( DamePrecioAlmuerzo()<= 0.0 )
        {
            uAccesibilidad.MuestraMensaje("El Precio del Almuerzo debe ser mayor a 0.");
            txtAlmuerzo.requestFocus();
            txtAlmuerzo.selectAll();
        }
    }
    
    public boolean DatosCompletos()
    {
        boolean bOk = true;
        
        if ( txtHoras.getText().isEmpty() || txtDescripcion.getText().isEmpty() || 
             txtPrecioSala.getText().isEmpty() || txtCoffe.getText().isEmpty()  ||
             txtAlmuerzo.getText().isEmpty() )
        {
            bOk = false;
        }
        
        bOk &= ( DameTotalHoras() > 0 ) && 
               ( ( DamePrecioCoffe() > 0.0 ) && ( DamePrecioAlmuerzo() > 0.0 ) && ( DamePrecioSala() > 0.0 ) );
        
        return bOk;
    }
    
    public int DameTotalHoras()
    {
        int iHoras = 0;
        
        try
        {
            iHoras = Integer.parseInt(txtHoras.getText());
        }
        catch ( Exception e )
        {
            iHoras = 0;
        }
        
        return iHoras;
    }
    
    public double DamePrecioSala()
    {
        double dPrecio = 0.0;
        
        try
        {
            dPrecio = Double.parseDouble(txtPrecioSala.getText());
        }
        catch ( Exception e )
        {
            dPrecio = 0.0;
        }
        
        return dPrecio;
                
    }
    
    public double DamePrecioCoffe()
    {
        double dPrecio = 0.0;
        
        try
        {
            dPrecio = Double.parseDouble(txtCoffe.getText());
        }
        catch ( Exception e )
        {
            dPrecio = 0.0;
        }
        
        return dPrecio;    
    }
    
    public double DamePrecioAlmuerzo()
    {
        double dPrecio = 0.0;
        
        try
        {
            dPrecio = Double.parseDouble(txtAlmuerzo.getText());
        }
        catch ( Exception e )
        {
            dPrecio = 0.0;
        }
        
        return dPrecio;    
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        // TODO add your handling code here:
        LimpiaCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void txtHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasKeyTyped
        // TODO add your handling code here:
        char cCaracter = evt.getKeyChar();        
        
        // Verificar si la tecla pulsada no es un digito        
        if ( !Character.isDigit(cCaracter) /*|| cCaracter == '0'*/ )
        {
            evt.consume();  // ignorar el evento de teclado
        }     
    }//GEN-LAST:event_txtHorasKeyTyped

    private void txtPrecioSalaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioSalaFocusGained
        // TODO add your handling code here:
        txtPrecioSala.setText(null);
    }//GEN-LAST:event_txtPrecioSalaFocusGained

    private void txtCoffeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCoffeFocusGained
        // TODO add your handling code here:
        txtCoffe.setText(null);
    }//GEN-LAST:event_txtCoffeFocusGained

    private void txtAlmuerzoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlmuerzoFocusGained
        // TODO add your handling code here:
        txtAlmuerzo.setText(null);
    }//GEN-LAST:event_txtAlmuerzoFocusGained

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtDescripcionKeyPressed
    {//GEN-HEADEREND:event_txtDescripcionKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) ) 
        {
            txtHoras.requestFocus();
        }
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtHorasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtHorasKeyPressed
    {//GEN-HEADEREND:event_txtHorasKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) ) 
        {
            txtPrecioSala.requestFocus();
       }
    }//GEN-LAST:event_txtHorasKeyPressed

    private void txtPrecioSalaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPrecioSalaKeyPressed
    {//GEN-HEADEREND:event_txtPrecioSalaKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) ) 
        {
            txtCoffe.requestFocus();
        }
    }//GEN-LAST:event_txtPrecioSalaKeyPressed

    private void txtCoffeKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCoffeKeyPressed
    {//GEN-HEADEREND:event_txtCoffeKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) ) 
        {
            txtAlmuerzo.requestFocus();
        }
    }//GEN-LAST:event_txtCoffeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                FrmDetPaquete dialog = new FrmDetPaquete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() 
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) 
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField txtAlmuerzo;
    private javax.swing.JFormattedTextField txtCoffe;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JFormattedTextField txtPrecioSala;
    // End of variables declaration//GEN-END:variables
}
