/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Modelo.Bitacora;
import Modelo.Descuento;
import Modelo.Usuario;
import Modelo.Utilerias;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
/**
 *
 * @author WIN7UTL64
 */
public class FrmDetEmpresasDesctos extends javax.swing.JDialog 
{
    private boolean Agregar = true;
    private Descuento Empresa = null;
    private Utilerias uAccesibilidad = null;  
    private Usuario uUsuario = Usuario.ObtenInstancia();
    private Bitacora uBitacora = Bitacora.ObtenInstancia();
    
    /**
     * Creates new form FrmDetEmpresasDesctos
     */
    public FrmDetEmpresasDesctos(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        AsignaEventosBotonesVentana();
        this.Empresa = new Descuento();
        this.uAccesibilidad = new Utilerias();
    }
    
    public FrmDetEmpresasDesctos(java.awt.Frame parent, boolean modal, int iIDEmpresaAux) 
    {
        super(parent, modal);
        initComponents();        
        AsignaEventosBotonesVentana();
        this.Empresa = new Descuento();
        this.Empresa.InstanciaEmpresaDescuentos(iIDEmpresaAux);
        this.uAccesibilidad = new Utilerias();
        this.Agregar = false;
        LlenaForma();        
    }
    
    public void AsignaEventosBotonesVentana()
    {
        Action btnAccionPagar = new AbstractAction("PAGAR") 
        {
            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnAceptarActionPerformed(evt);
            }
        };       

        Action btnAccionCancelar = new AbstractAction("CERRAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnCancelarActionPerformed(evt);
            }
        };
               
         
        btnAceptar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "Aceptar"); 
        btnAceptar.getActionMap().put("Aceptar", btnAccionPagar);        
        btnCancelar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "Cancelar"); 
        btnCancelar.getActionMap().put("Cancelar", btnAccionCancelar);         
    }

    public void LlenaForma()
    {
        txtNombreEmpresa.setText(Empresa.getEmpresa());
        txtDescuentoEmpresa.setText(String.valueOf(Empresa.getDescuento()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescuentoEmpresa = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta empresa con descuento");
        setModal(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descuentos para Empresas"));

        jLabel1.setDisplayedMnemonic('e');
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setLabelFor(txtNombreEmpresa);
        jLabel1.setText("Empresa:");

        txtNombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtNombreEmpresaKeyReleased(evt);
            }
        });

        jLabel2.setDisplayedMnemonic('d');
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setLabelFor(txtDescuentoEmpresa);
        jLabel2.setText("Descuento:");

        txtDescuentoEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtDescuentoEmpresa.setToolTipText("Máximo 50% de Descuento");
        txtDescuentoEmpresa.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtDescuentoEmpresaKeyTyped(evt);
            }
        });

        jLabel3.setDisplayedMnemonic('d');
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setLabelFor(txtDescuentoEmpresa);
        jLabel3.setText("Máximo 50 %");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDescuentoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescuentoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar (F4)");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Aceptar (F3)");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        GuardarDatos();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreEmpresaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreEmpresaKeyReleased
    {//GEN-HEADEREND:event_txtNombreEmpresaKeyReleased
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt)) 
        {
            txtDescuentoEmpresa.requestFocus();
        }
    }//GEN-LAST:event_txtNombreEmpresaKeyReleased

    private void txtDescuentoEmpresaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtDescuentoEmpresaKeyTyped
    {//GEN-HEADEREND:event_txtDescuentoEmpresaKeyTyped
        // TODO add your handling code here:char cCaracter = evt.getKeyChar();        
        char cCaracter = evt.getKeyChar();
        
        if ( txtDescuentoEmpresa.getText().length() == 2 || !Character.isDigit(cCaracter) )
        {
            evt.consume();
        }        
    }//GEN-LAST:event_txtDescuentoEmpresaKeyTyped

    public void GuardarDatos()
    {
        if ( CamposLlenos() )
        {
            Empresa.setEmpresa(txtNombreEmpresa.getText());
            Empresa.setDescuento(Double.parseDouble(txtDescuentoEmpresa.getText()));
            
            if ( this.Agregar )
            {
                if ( Empresa.Insertar() )
                {
                    uAccesibilidad.MuestraMensaje("Empresa agregada correctamente");
                    uBitacora.InsertarAccion(uUsuario.getID(), "EL USUARIO: " + uUsuario.getNomUsuario() + " AGREGÓ EMPRESA: " + txtNombreEmpresa.getText() , "DETALLE DE EMPRESAS", Bitacora.AGREGAR_EMPRESADESCTO);
                    this.dispose();
                }
                else
                {
                    uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de Agregar la Empresa.");
                }
            }
            else
            {
                if ( Empresa.Actualizar())
                {
                    uAccesibilidad.MuestraMensaje("Empresa actualizada correctamente");
                    uBitacora.InsertarAccion(uUsuario.getID(), "EL USUARIO: " + uUsuario.getNomUsuario() + " EDITÓ INFORMACIÓN DE LA EMPRESA: " + txtNombreEmpresa.getText() , "DETALLE DE EMPRESAS", Bitacora.EDITAR_EMPRESADESCTO);
                    this.dispose();
                }
                else
                {
                    uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de Actualizar la Empresa.");
                }
            }
        }
        else
        {
            MuestraError();
        }
    }
    
    public void MuestraError()
    {
        if ( txtNombreEmpresa.getText().isEmpty() )
        {
            uAccesibilidad.MuestraMensaje("El nombre de la Empresa no puede estar vacío.");
            txtNombreEmpresa.requestFocus();
            txtNombreEmpresa.selectAll();
        }
        else if ( txtDescuentoEmpresa.getText().isEmpty() || !DescuentoValido() )
        { 
            uAccesibilidad.MuestraMensaje("El descuento para la Empresa debe estar entre el 1 y el 50 %.");
            txtDescuentoEmpresa.requestFocus();
            txtDescuentoEmpresa.selectAll();
        }        
    }
    
    public double DameDescuentoIngresado()
    {
        double dDescuento = 0.0;
        
        try
        {
            dDescuento = Double.parseDouble(txtDescuentoEmpresa.getText());
        }
        catch ( Exception e )
        {
            dDescuento = 0.0;
        }
        
        return dDescuento;
    }
    
    public boolean DescuentoValido()
    {
        return ( DameDescuentoIngresado() >= 0 && DameDescuentoIngresado() <= 50 );
    }
    
    public boolean CamposLlenos()
    {
        boolean bOk = true;
        
        if ( txtNombreEmpresa.getText().isEmpty() || txtDescuentoEmpresa.getText().isEmpty() || ( !DescuentoValido() ) || DameDescuentoIngresado() == 0.0 )
        {
            bOk = false;
        }
        
        return bOk;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetEmpresasDesctos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetEmpresasDesctos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetEmpresasDesctos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetEmpresasDesctos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDetEmpresasDesctos dialog = new FrmDetEmpresasDesctos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtDescuentoEmpresa;
    private javax.swing.JTextField txtNombreEmpresa;
    // End of variables declaration//GEN-END:variables
}
