/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Modelo.Bitacora;
import Modelo.Usuario;
import Modelo.Utilerias;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author WIN7UTL64
 */
public class FrmDetalleRecepcionista extends javax.swing.JDialog 
{
    private Utilerias uAccesibilidad;    
    private Usuario uUsuario = Usuario.ObtenInstancia();
    private Bitacora bBitacora = Bitacora.ObtenInstancia();    
    private boolean Agregar = true;
    private int IDUsuarioEdicion = 0;
    private String SentenciaSQLActualizacion = null;
    
    /**
     * Creates new form FrmDetalleRecepcionista
     */
    public FrmDetalleRecepcionista(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        AsignaEventosBotonesVentana();
        uAccesibilidad = new Utilerias();
    }   
    
    public FrmDetalleRecepcionista(java.awt.Frame parent, boolean modal, int iIdUsuario) 
    {
        super(parent, modal);
        initComponents();
        AsignaEventosBotonesVentana();
        uAccesibilidad = new Utilerias();
        this.Agregar = false;
        this.IDUsuarioEdicion = iIdUsuario;
        this.SentenciaSQLActualizacion = null;
        LlenaForma(iIdUsuario);
    }
    
    public void AsignaEventosBotonesVentana()
    {
        Action btnAccionPagar = new AbstractAction("PAGAR") 
        {
            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnAceptarActionPerformed(evt);
            }
        };       

        Action btnAccionCancelar = new AbstractAction("CERRAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnCancelarActionPerformed(evt);
            }
        };
               
         
        btnAceptar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "Aceptar"); 
        btnAceptar.getActionMap().put("Aceptar", btnAccionPagar);        
        btnCancelar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "Cancelar"); 
        btnCancelar.getActionMap().put("Cancelar", btnAccionCancelar);         
    }
    
    public void LlenaForma(int iID)
    {
        ResultSet rsResultado = null;
        
        try
        {
            rsResultado = uUsuario.DameInstanciaEdicionUsuario(iID);
            
            if ( rsResultado != null )
            {
                rsResultado.next();                
                txtUsuario.setText(rsResultado.getString("USUARIO"));
                txtUsuario.setEnabled(false);
                txtContrasenia.setText(rsResultado.getString("CONTRASENIA"));
                txtNombre.setText(rsResultado.getString("NOMBRE"));
                txtApPaterno.setText(rsResultado.getString("AP_PATERNO"));
                txtApMaterno.setText(rsResultado.getString("AP_MATERNO"));
                txtTelefono.setText(rsResultado.getString("TELEFONO"));
                txtEmail.setText(rsResultado.getString("EMAIL"));
                txtDireccion.setText(rsResultado.getString("DIRECCION"));
                
                if ( rsResultado.getInt("TIPO") == 0 )
                {
                    rbtnAdministrador.setSelected(true);
                }
                else
                {
                    rbtnRecepcionista.setSelected(true);
                }
            }
        }
        catch ( Exception e )
        {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnGrupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtApMaterno = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        rbtnRecepcionista = new javax.swing.JRadioButton();
        rbtnAdministrador = new javax.swing.JRadioButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Recepcionista"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Acceso"));

        jLabel1.setDisplayedMnemonic('u');
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setLabelFor(txtUsuario);
        jLabel1.setText("Usuario:");

        jLabel2.setDisplayedMnemonic('c');
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setLabelFor(txtContrasenia);
        jLabel2.setText("Contraseña:");

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtUsuarioKeyPressed(evt);
            }
        });

        txtContrasenia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtContraseniaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setDisplayedMnemonic('n');
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setLabelFor(txtNombre);
        jLabel3.setText("Nombre:");

        jLabel4.setDisplayedMnemonic('p');
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setLabelFor(txtApPaterno);
        jLabel4.setText("Apellido Paterno:");

        jLabel5.setDisplayedMnemonic('m');
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setLabelFor(txtApMaterno);
        jLabel5.setText("Apellido Materno:");

        jLabel6.setDisplayedMnemonic('t');
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setLabelFor(txtTelefono);
        jLabel6.setText("Teléfono:");

        jLabel7.setDisplayedMnemonic('e');
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setLabelFor(txtEmail);
        jLabel7.setText("Email:");

        jLabel8.setDisplayedMnemonic('d');
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setLabelFor(txtDireccion);
        jLabel8.setText("Dirección:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyPressed(evt);
            }
        });

        txtApPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtApPaternoKeyPressed(evt);
            }
        });

        txtApMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtApMaternoKeyPressed(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtTelefonoKeyPressed(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtEmailKeyPressed(evt);
            }
        });

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Tipo:");

        btnGrupoBotones.add(rbtnRecepcionista);
        rbtnRecepcionista.setSelected(true);
        rbtnRecepcionista.setText("Recepcionista");

        btnGrupoBotones.add(rbtnAdministrador);
        rbtnAdministrador.setText("Administrador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnAdministrador)
                            .addComponent(rbtnRecepcionista)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtApMaterno, txtApPaterno, txtNombre});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmail, txtTelefono});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnRecepcionista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnAdministrador))
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Aceptar (F3)");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar (F4)");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        InsertarDatos();
    }//GEN-LAST:event_btnAceptarActionPerformed

    public void ErrorUsuarioExistente()
    {
        uAccesibilidad.MuestraMensaje("El Usuario ya existe, favor de ingresar otro.");
        txtUsuario.requestFocus();
        txtUsuario.selectAll();
    }
    
    public void InstanciaUsuario()
    {
        if ( this.Agregar )
        {
            uUsuario.setNomUsuario(txtUsuario.getText());
            uUsuario.setContrasenia(txtContrasenia.getText());
            uUsuario.setNombre(txtNombre.getText());
            uUsuario.setApPaterno(txtApPaterno.getText());
            uUsuario.setApMaterno(txtApMaterno.getText());
            uUsuario.setTelefono(txtTelefono.getText());
            uUsuario.setEmail(txtEmail.getText());
            uUsuario.setDireccion(txtDireccion.getText());

            if ( rbtnRecepcionista.isSelected() )
            {
                uUsuario.setTipo(1);
            }
            else
            {
                uUsuario.setTipo(0);
            }
        }
        else
        {
            this.SentenciaSQLActualizacion = "UPDATE USUARIOS SET ";
            this.SentenciaSQLActualizacion += " USUARIO = '" + txtUsuario.getText() + "', ";
            this.SentenciaSQLActualizacion += " CONTRASENIA = '" + txtContrasenia.getText() + "', ";
            
            if ( rbtnRecepcionista.isSelected() )
            {
                this.SentenciaSQLActualizacion += " TIPO = 1, ";
            }
            else
            {
                this.SentenciaSQLActualizacion += " TIPO = 0, ";
            }
            
            this.SentenciaSQLActualizacion += " NOMBRE = '" + txtNombre.getText()+ "', ";
            this.SentenciaSQLActualizacion += " AP_PATERNO = '" + txtApPaterno.getText() + "', ";
            this.SentenciaSQLActualizacion += " AP_MATERNO = '" + txtApMaterno.getText() + "', ";
            this.SentenciaSQLActualizacion += " TELEFONO = '" + txtTelefono.getText() + "', ";
            this.SentenciaSQLActualizacion += " EMAIL = '" + txtEmail.getText() + "', ";
            this.SentenciaSQLActualizacion += " DIRECCION = '" + txtDireccion.getText() + "' ";
            this.SentenciaSQLActualizacion += " WHERE ID = " + this.IDUsuarioEdicion;
        }
    }
    
    public void LimpiaCampos()
    {
        txtUsuario.setText(null);
        txtContrasenia.setText(null);
        txtNombre.setText(null);
        txtApPaterno.setText(null);
        txtApMaterno.setText(null);
        txtTelefono.setText(null);
        txtEmail.setText(null);
        txtDireccion.setText(null);
        txtUsuario.requestFocus();
    }
    
    public void InsertarDatos()
    {
        if ( ValidaDatos() )
        {
            if ( ( this.Agregar ) ? ( !uUsuario.ExisteUsuario(txtUsuario.getText()) ) : true )
            {                
                InstanciaUsuario();
                
                if ( this.Agregar )
                {
                    if ( uUsuario.Insertar() )
                    {
                        uAccesibilidad.MuestraMensaje("Usuario agregado correctamente.");
                        LimpiaCampos();
                    }
                    else
                    {
                        uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de insertar al Usuario.");
                    }
                }
                else
                {
                    if ( uUsuario.Actualizar(this.SentenciaSQLActualizacion) )
                    {
                        uAccesibilidad.MuestraMensaje("Usuario editado correctamente.");
                        this.dispose();
                    }
                    else
                    {
                        uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de editar al Usuario.");
                    }
                }
            }
            else
            {
                ErrorUsuarioExistente();
            }
        }
        else
        {
            MuestraMensajeError();
        }
    }
    
    public void MuestraMensajeError()
    {
        if ( txtUsuario.getText().isEmpty() )
        {
            txtUsuario.requestFocus();
            txtUsuario.selectAll();
            uAccesibilidad.MuestraMensaje("El campo 'Usuario' no puede estar vacío.");
        }
        else if ( txtContrasenia.getText().isEmpty() )
        {
            txtContrasenia.requestFocus();
            txtContrasenia.selectAll();
            uAccesibilidad.MuestraMensaje("El campo 'Contraseña' no puede estar vacío.");
        }
        else if ( txtNombre.getText().isEmpty() ) 
        {
            txtNombre.requestFocus();
            txtNombre.selectAll();
            uAccesibilidad.MuestraMensaje("El campo 'Nombre' no puede estar vacío.");
        }
        else if ( txtApPaterno.getText().isEmpty() )
        {
            txtApPaterno.requestFocus();
            txtApPaterno.selectAll();
            uAccesibilidad.MuestraMensaje("El campo 'Apellido Paterno' no puede estar vacío.");
        }
        else if ( txtTelefono.getText().isEmpty() )
        {
            txtTelefono.requestFocus();
            txtTelefono.selectAll();
            uAccesibilidad.MuestraMensaje("El campo 'Teléfono' no puede estar vacío.");
        }
        else if ( txtDireccion.getText().isEmpty() )
        {
            txtDireccion.requestFocus();
            txtDireccion.selectAll();
            uAccesibilidad.MuestraMensaje("El campo 'Dirección' no puede estar vacío.");
        }         
    }
    
    public boolean ValidaDatos()            
    {
        boolean bOk = false;
        
        bOk = ( !txtUsuario.getText().isEmpty()  && !txtContrasenia.getText().isEmpty() &&
                !txtNombre.getText().isEmpty()   && !txtApPaterno.getText().isEmpty()   && 
                !txtTelefono.getText().isEmpty() && !txtDireccion.getText().isEmpty() );
        
        return bOk;
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:        
        Salir();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtUsuarioKeyPressed
    {//GEN-HEADEREND:event_txtUsuarioKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtContrasenia.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtContraseniaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtContraseniaKeyPressed
    {//GEN-HEADEREND:event_txtContraseniaKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_txtContraseniaKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyPressed
    {//GEN-HEADEREND:event_txtNombreKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtApPaterno.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApPaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtApPaternoKeyPressed
    {//GEN-HEADEREND:event_txtApPaternoKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtApMaterno.requestFocus();
        }
    }//GEN-LAST:event_txtApPaternoKeyPressed

    private void txtApMaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtApMaternoKeyPressed
    {//GEN-HEADEREND:event_txtApMaternoKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtTelefono.requestFocus();
        }
    }//GEN-LAST:event_txtApMaternoKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtTelefonoKeyPressed
    {//GEN-HEADEREND:event_txtTelefonoKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtEmailKeyPressed
    {//GEN-HEADEREND:event_txtEmailKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtDireccion.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    public void Salir()
    {
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDetalleRecepcionista dialog = new FrmDetalleRecepcionista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGrupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnAdministrador;
    private javax.swing.JRadioButton rbtnRecepcionista;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
