/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Controlador.FormatoTabla;
import Modelo.Huesped;
import Modelo.TablaModelo;
import Modelo.Utilerias;
import java.awt.Cursor;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author LCC Luis Alberto Flores Castillo <luis.ejob@gmail.com>
 */
public class FrmListaHuespedes extends javax.swing.JDialog
{
    private boolean PresionoAceptar;
    private int IdHuesped;
    private String Nombre;
    private String ApPaterno;
    private String ApMaterno;
    private String Telefono;
    private Utilerias uAccesibilidad;
    private Huesped Cliente = null;
    private TablaModelo dtmTabla;
    /**
     * Creates new form FrmListaHuespedes
     */
    public FrmListaHuespedes(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.uAccesibilidad = new Utilerias();
        this.Cliente = new Huesped();
        RefrescarForma();
    }

    public void RefrescarForma()
    {
        try
        {                                  
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));  
            tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tblClientes.doLayout();                        
            dtmTabla = new TablaModelo(null, GetColumnas());                        
            tblClientes.setDefaultRenderer (Object.class, new FormatoTabla() );
            InicializarFilas();            
            tblClientes.setModel(dtmTabla);            
            tblClientes.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
            AjustaColumnas();         
            this.setCursor(Cursor.getDefaultCursor());
            tblClientes.changeSelection(0, 1, false, false);
        }
        catch ( Exception e )
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al llenar el Catálogo");
        }
    }
    
    public void AjustaColumnas()
    {
        TableColumnModel tblModeloColumnas = tblClientes.getColumnModel();
        
        tblModeloColumnas.getColumn(0).setPreferredWidth(100);
        tblModeloColumnas.getColumn(1).setPreferredWidth(100);
        tblModeloColumnas.getColumn(2).setPreferredWidth(100);
        tblModeloColumnas.getColumn(3).setPreferredWidth(100);
        tblModeloColumnas.getColumn(4).setPreferredWidth(100);
    }
    
    public void InicializarFilas()
    {                        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));        
        Cliente.DameRegistrosListaHuespedes(dtmTabla, GetColumnas());        
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    public String[] GetColumnas()
    {                        
        String strColumnas[] = new String[]{"Id"/*0*/, "Nombre"/*1*/, "Apellido Paterno"/*2*/, "Apellido Materno"/*3*/, "Teléfono"/*4*/};
        
        return strColumnas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Húespedes registrados");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Húespedes"));

        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tblClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Agregar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tblClientesKeyPressed
    {//GEN-HEADEREND:event_tblClientesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblClientesKeyPressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        AsignaDatos();
    }//GEN-LAST:event_btnAceptarActionPerformed

    public void AsignaDatos()
    {
        if ( tblClientes != null )
        {        
            this.IdHuesped = Integer.parseInt(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString());
            this.Nombre = tblClientes.getValueAt(tblClientes.getSelectedRow(), 1).toString();
            this.ApPaterno = tblClientes.getValueAt(tblClientes.getSelectedRow(), 2).toString();
            this.ApMaterno = tblClientes.getValueAt(tblClientes.getSelectedRow(), 3).toString();
            this.Telefono = tblClientes.getValueAt(tblClientes.getSelectedRow(), 4).toString();
        }        
        
        this.PresionoAceptar = true;
        this.dispose();
    }

    public int getIdHuesped()
    {
        return IdHuesped;
    }

    public void setIdHuesped(int IdHuesped)
    {
        this.IdHuesped = IdHuesped;
    }

    public String getNombre()
    {
        return Nombre;
    }

    public void setNombre(String Nombre)
    {
        this.Nombre = Nombre;
    }

    public String getApPaterno()
    {
        return ApPaterno;
    }

    public void setApPaterno(String ApPaterno)
    {
        this.ApPaterno = ApPaterno;
    }

    public String getApMaterno()
    {
        return ApMaterno;
    }

    public void setApMaterno(String ApMaterno)
    {
        this.ApMaterno = ApMaterno;
    }

    public String getTelefono()
    {
        return Telefono;
    }

    public void setTelefono(String Telefono)
    {
        this.Telefono = Telefono;
    }            

    public boolean isPresionoAceptar()
    {
        return PresionoAceptar;
    }

    public void setPresionoAceptar(boolean PresionoAceptar)
    {
        this.PresionoAceptar = PresionoAceptar;
    }        
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.PresionoAceptar = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmListaHuespedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmListaHuespedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmListaHuespedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmListaHuespedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {                
                FrmListaHuespedes dialog = new FrmListaHuespedes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
