/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Controlador.ControlHabitaciones;
import Modelo.Habitacion;
import Modelo.SalaConferencias;
import Modelo.Utilerias;
import Modelo.UtileriasSalaConferencias;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Usuario
 */
public class FrmListaSalaConferencias extends javax.swing.JInternalFrame //implements Runnable
{    
    private SalaConferencias scSala;
    private Utilerias uAccesibilidad;
    
    /**
     * Creates new form FrmListaHabitaciones
     */
    public FrmListaSalaConferencias()
    {                
        initComponents();           
        scSala = new SalaConferencias();
        uAccesibilidad = new Utilerias();                        
    }

    public void RevisaEstado()
    {        
        Timer timer = new Timer();
        timer.schedule(new UtileriasSalaConferencias(this.getParent()), 0, 60000); //1 minuto
        //timer.schedule(new UtileriasSalaConferencias(this.getParent()), 0, 1000); //1 segundo
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        miMenuLimpiar = new javax.swing.JMenuItem();
        miMenuReservar = new javax.swing.JMenuItem();
        miMenuDetalleHabitacion = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        PanelHabitacion_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelEdoH1 = new javax.swing.JLabel();
        btnAceptarH1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnSalirIzquierda = new javax.swing.JButton();

        miMenuLimpiar.setText("Servicio de limpieza");
        miMenuLimpiar.setToolTipText("Enviar servicio de limpieza a la habitación");
        miMenuLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMenuLimpiarActionPerformed(evt);
            }
        });
        popMenu.add(miMenuLimpiar);

        miMenuReservar.setText("Reservar Sala de Conferencias");
        miMenuReservar.setToolTipText("Generar una reservación para la Sala de Conferencias");
        miMenuReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMenuReservarActionPerformed(evt);
            }
        });
        popMenu.add(miMenuReservar);

        miMenuDetalleHabitacion.setText("Editar Habitación");
        miMenuDetalleHabitacion.setToolTipText("");
        miMenuDetalleHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMenuDetalleHabitacionActionPerformed(evt);
            }
        });
        popMenu.add(miMenuDetalleHabitacion);

        setClosable(true);
        setIconifiable(true);
        setTitle("Salas de conferencias");
        setAutoscrolls(true);

        PanelHabitacion_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelHabitacion_1.setComponentPopupMenu(popMenu);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALA DE CONFERENCIAS");

        labelEdoH1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEdoH1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEdoH1.setText("DISPONIBLE");

        btnAceptarH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Habitacion_Disponible.png"))); // NOI18N
        btnAceptarH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarH1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHabitacion_1Layout = new javax.swing.GroupLayout(PanelHabitacion_1);
        PanelHabitacion_1.setLayout(PanelHabitacion_1Layout);
        PanelHabitacion_1Layout.setHorizontalGroup(
            PanelHabitacion_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addComponent(labelEdoH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHabitacion_1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarH1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        PanelHabitacion_1Layout.setVerticalGroup(
            PanelHabitacion_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHabitacion_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEdoH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptarH1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(PanelHabitacion_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(PanelHabitacion_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(738, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jToolBar1.setRollover(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReservarHabitacion48.png"))); // NOI18N
        jButton1.setText("Reservar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EntregarHabitacion48.png"))); // NOI18N
        jButton2.setText("Entregar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LimpiezaHabitacion48.png"))); // NOI18N
        jButton3.setText("Limpieza");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HabitacionMantenimiento48.png"))); // NOI18N
        jButton4.setText("Mantenimiento");
        jButton4.setToolTipText("Enviar una habitación a servicio de mantenimiento");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hospedajes_BarraIzquierda.png"))); // NOI18N
        jButton5.setText("Calendario");
        jButton5.setToolTipText("Enviar una habitación a servicio de mantenimiento");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        btnSalirIzquierda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalirIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salida48.png"))); // NOI18N
        btnSalirIzquierda.setText("Salir");
        btnSalirIzquierda.setToolTipText("");
        btnSalirIzquierda.setFocusable(false);
        btnSalirIzquierda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalirIzquierda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalirIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirIzquierdaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalirIzquierda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarH1ActionPerformed
        // TODO add your handling code here:
        //ReservarSalaDeConferencias();
        GenerarAccion();
    }//GEN-LAST:event_btnAceptarH1ActionPerformed

    public void LlenaSalaDeConferencias()
    {
        int iEstado = 0;
        
        iEstado = scSala.DameEstadoSalaDeConferencias();
        uAccesibilidad.ConfiguraElementosSalaConferencias(labelEdoH1, btnAceptarH1, iEstado);
    }
    
    private void miMenuLimpiarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miMenuLimpiarActionPerformed
    {//GEN-HEADEREND:event_miMenuLimpiarActionPerformed
        // TODO add your handling code here:
        uAccesibilidad.MuestraMensaje("En servicio...");
    }//GEN-LAST:event_miMenuLimpiarActionPerformed

    private void miMenuDetalleHabitacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miMenuDetalleHabitacionActionPerformed
    {//GEN-HEADEREND:event_miMenuDetalleHabitacionActionPerformed
        // TODO add your handling code here:
        FrmDetalleHabitacionD frm = new FrmDetalleHabitacionD(null, true, 1);
        
        frm.show();
    }//GEN-LAST:event_miMenuDetalleHabitacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReservarSalaDeConferencias();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void miMenuReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMenuReservarActionPerformed
        // TODO add your handling code here:
        ReservarSalaDeConferencias();
    }//GEN-LAST:event_miMenuReservarActionPerformed

    private void btnSalirIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirIzquierdaActionPerformed
        // TODO add your handling code here:
        Salir();
    }//GEN-LAST:event_btnSalirIzquierdaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EntregarSalaConferencias();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        EnviarALimpiezaSalaConferencias();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        // TODO add your handling code here:
        EnviarAMantenimientoSalaConferencias();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LlamaCalendario();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void LlamaCalendario()
    {
        CnsReservacionesSalaConf frm = new CnsReservacionesSalaConf(null, true);
        
        frm.show();
    }
    
    public void EnviarAMantenimientoSalaConferencias()
    {
        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Deseas enviar a la Sala de Conferencias a Mantenimiento?") == 0 )
        {
            if ( scSala.EnviarMantenimientoSalaConferencias() )
            {
                uAccesibilidad.MuestraMensaje("Registro actualizado correctamente.");
                uAccesibilidad.RepintaFormasEnMenu(this.getParent());
            }
            else
            {
                uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de actualizar los Datos.");
            }
        }
    }
    
    public void EnviarALimpiezaSalaConferencias()
    {
        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Deseas enviar a limpieza a la Sala de Conferencias?") == 0 )
        {
            if ( scSala.EnviarLimpiezaSalaConferencias() )
            {
                uAccesibilidad.MuestraMensaje("Registro actualizado correctamente.");
                uAccesibilidad.RepintaFormasEnMenu(this.getParent());
            }
            else
            {
                uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de actualizar los Datos.");
            }
        }
    }
    
    public void EntregarSalaConferencias()
    {
        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Deseas entregar la Sala de Conferencias?") == 0 )
        {
            if ( scSala.EntregarSalaConferencias() )
            {
                uAccesibilidad.MuestraMensaje("Registro actualizado correctamente.");
                uAccesibilidad.RepintaFormasEnMenu(this.getParent());
            }
            else
            {
                uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de actualizar los Datos.");
            }
        }                
    }
    
    public void Salir()
    {
        this.dispose();
    }
    
    public void GenerarAccion()
    {
        int iEstado = 0;
        
        iEstado = scSala.DameEstadoSalaDeConferencias();
        
        if ( iEstado == 0 )
        {
            ReservarSalaDeConferencias();
        }
        else if ( iEstado == 1 )
        {
            EntregarSalaConferencias();
        }
        else if ( iEstado == 3 || iEstado == 4 )
        {
            LiberarSalaConferencias();
        }
    }
    
    public void LiberarSalaConferencias()
    {
        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Deseas dejar Disponible la Sala de Conferencias?") == 0 )
        {
            if ( scSala.LiberaSalaDeConferencias())
            {
                uAccesibilidad.MuestraMensaje("Registro actualizado correctamente.");
                uAccesibilidad.RepintaFormasEnMenu(this.getParent());
            }
            else
            {
                uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de actualizar los Datos.");
            }
        }
    }
    
    public void ReservarSalaDeConferencias()
    {        
        FrmReservarSalaConferencias frm = new FrmReservarSalaConferencias(null, true);
        
        frm.show();
        uAccesibilidad.RepintaFormasEnMenu(this.getParent());
    }        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHabitacion_1;
    private javax.swing.JButton btnAceptarH1;
    private javax.swing.JButton btnSalirIzquierda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelEdoH1;
    private javax.swing.JMenuItem miMenuDetalleHabitacion;
    private javax.swing.JMenuItem miMenuLimpiar;
    private javax.swing.JMenuItem miMenuReservar;
    private javax.swing.JPopupMenu popMenu;
    // End of variables declaration//GEN-END:variables
/*   
    @Override
    public void run() //Thread
    {
        try
        {
            System.out.println("Entro a run()");
            Thread.sleep(60000); //1 minuto.            
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
        
        this.RevisaEstado();
        System.out.println("Salgo de run");
    }
    */
}
