/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Modelo.Descuento;
import Modelo.Paquete;
import Modelo.SalaConferencias;
import Modelo.Utilerias;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author WIN7UTL64
 */
public class FrmReservarSalaConferencias extends javax.swing.JDialog 
{    
    private int Empresa;
    private double Descuento;
    private Paquete pPaquete;    
    private SalaConferencias scSala;
    private Utilerias uAccesibilidad;
    
    /**
     * Creates new form FrmReservarSalaConferencias
     */
    public FrmReservarSalaConferencias(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        AsignaEventosBotonesVentana();
        uAccesibilidad = new Utilerias();
        pPaquete = new Paquete();        
        scSala = new SalaConferencias();
        btnSoloSala.setSelected(true);
        ConfiguraForma();
    }

    public void ConfiguraForma()
    {
        int iHoras = 0;
        int iMinutos = 0;
        int iSegundos = 0;
        Calendar cCalendario = Calendar.getInstance();
        Date dtFecha = new Date();
        
        dtFechaRegistro.setDate(dtFecha);
        iHoras = cCalendario.get(Calendar.HOUR_OF_DAY);
        iMinutos = cCalendario.get(Calendar.MINUTE);
        iSegundos = cCalendario.get(Calendar.SECOND);
        txtHoraRegistro.setText(iHoras + ":" + iMinutos + ":" + iSegundos );
        //txtHoraReservacion.setText(iHoras + ":" + iMinutos + " " + uAccesibilidad.DameAmPM(iHoras));
    }
    
    public void AsignaEventosBotonesVentana()
    {
        Action btnAccionPagar = new AbstractAction("PAGAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnAceptarActionPerformed(evt);
            }
        };

        Action btnAccionLimpiar = new AbstractAction("LIMPIAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnListarReservacionesActionPerformed(evt);
            }
        };

        Action btnAccionCancelar = new AbstractAction("CERRAR") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnCancelarActionPerformed(evt);
            }
        };       
        
        Action btnAccionPaquetes = new AbstractAction("Paquete") 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnPaqueteActionPerformed(evt);
            }
        };
        
        Action btnAccionEmpresa = new AbstractAction("Empresa")
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                btnEmpresasActionPerformed(evt);
            }
        };
         
        btnAceptar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "Pagar"); 
        btnAceptar.getActionMap().put("Pagar", btnAccionPagar);
        btnListarReservaciones.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "Limpiar"); 
        btnListarReservaciones.getActionMap().put("Limpiar", btnAccionLimpiar);
        btnCancelar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "Cancelar"); 
        btnCancelar.getActionMap().put("Cancelar", btnAccionCancelar); 
        btnEmpresas.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "F5"); 
        btnEmpresas.getActionMap().put("F5", btnAccionEmpresa);         
        btnPaquete.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "F2"); 
        btnPaquete.getActionMap().put("F2", btnAccionPaquetes);         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bgGrupo = new javax.swing.ButtonGroup();
        jTimeChooserDemo1 = new lu.tudor.santec.jtimechooser.demo.JTimeChooserDemo();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPaquete = new javax.swing.JTextField();
        btnPaquete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTotalPersonas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTiempoReservado = new javax.swing.JTextField();
        btnSoloSala = new javax.swing.JRadioButton();
        btnCoffee = new javax.swing.JRadioButton();
        btnAlmuerzo = new javax.swing.JRadioButton();
        labelSubTotal1 = new javax.swing.JLabel();
        txtPrecioSala = new javax.swing.JFormattedTextField();
        labelSubTotal2 = new javax.swing.JLabel();
        txtPrecioCoffe = new javax.swing.JFormattedTextField();
        labelSubTotal3 = new javax.swing.JLabel();
        txtPrecioPorPersona = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtFechaRegistro = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtHoraRegistro = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dtFechaReservacion = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtHoraReservacion = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jPanel4 = new javax.swing.JPanel();
        cboxAnticipo = new javax.swing.JCheckBox();
        cmbboxPorcentaje = new javax.swing.JComboBox();
        labelPorcentaje = new javax.swing.JLabel();
        cboxDescuentoEmpresas = new javax.swing.JCheckBox();
        labelNombreEmpresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        btnEmpresas = new javax.swing.JButton();
        labelDescuento = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        labelSubTotal = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JFormattedTextField();
        labelEtiqDescuento = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JFormattedTextField();
        labelTotalAPagar = new javax.swing.JLabel();
        txtTotal = new javax.swing.JFormattedTextField();
        labelAnticipo = new javax.swing.JLabel();
        txtAnticipo = new javax.swing.JFormattedTextField();
        btnListarReservaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar reservación para la Sala de Conferencias");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del paquete"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Paquete");

        txtPaquete.setEnabled(false);

        btnPaquete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPaquete.setText("F2");
        btnPaquete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPaqueteActionPerformed(evt);
            }
        });

        jLabel10.setDisplayedMnemonic('p');
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setLabelFor(txtTotalPersonas);
        jLabel10.setText("Total de personas:");

        txtTotalPersonas.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtTotalPersonasFocusLost(evt);
            }
        });
        txtTotalPersonas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtTotalPersonasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtTotalPersonasKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Horas Reservadas:");

        txtTiempoReservado.setEnabled(false);

        bgGrupo.add(btnSoloSala);
        btnSoloSala.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSoloSala.setText("Sólo la renta de la sala");
        btnSoloSala.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSoloSalaActionPerformed(evt);
            }
        });

        bgGrupo.add(btnCoffee);
        btnCoffee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCoffee.setText("Con Coffe Break");
        btnCoffee.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCoffeeActionPerformed(evt);
            }
        });

        bgGrupo.add(btnAlmuerzo);
        btnAlmuerzo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlmuerzo.setText("Con almuerzo");
        btnAlmuerzo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAlmuerzoActionPerformed(evt);
            }
        });

        labelSubTotal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSubTotal1.setText("Sala:");

        txtPrecioSala.setEditable(false);
        txtPrecioSala.setForeground(new java.awt.Color(0, 51, 255));
        txtPrecioSala.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecioSala.setCaretColor(new java.awt.Color(51, 51, 255));
        txtPrecioSala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        labelSubTotal2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSubTotal2.setText("Coffee Break:");

        txtPrecioCoffe.setEditable(false);
        txtPrecioCoffe.setForeground(new java.awt.Color(0, 51, 255));
        txtPrecioCoffe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecioCoffe.setCaretColor(new java.awt.Color(51, 51, 255));
        txtPrecioCoffe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        labelSubTotal3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSubTotal3.setText("Almuerzo por Persona:");

        txtPrecioPorPersona.setEditable(false);
        txtPrecioPorPersona.setForeground(new java.awt.Color(0, 51, 255));
        txtPrecioPorPersona.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecioPorPersona.setCaretColor(new java.awt.Color(51, 51, 255));
        txtPrecioPorPersona.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSoloSala)
                                .addGap(29, 29, 29)
                                .addComponent(btnCoffee)
                                .addGap(72, 72, 72)
                                .addComponent(btnAlmuerzo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(77, 77, 77)
                                .addComponent(txtPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPaquete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTiempoReservado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSubTotal3)
                    .addComponent(labelSubTotal1)
                    .addComponent(labelSubTotal2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecioPorPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPrecioCoffe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecioSala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaquete))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTiempoReservado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotalPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSoloSala)
                    .addComponent(btnCoffee)
                    .addComponent(btnAlmuerzo)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubTotal1)
                    .addComponent(txtPrecioSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecioCoffe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubTotal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioPorPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubTotal3)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos reservación"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Fecha de registro:");

        dtFechaRegistro.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Hora de registro:");

        txtHoraRegistro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txtHoraRegistro.setEnabled(false);

        jLabel3.setDisplayedMnemonic('n');
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setLabelFor(txtNombre);
        jLabel3.setText("Nombre / Razón Social:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyPressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Reservación"));

        jLabel5.setDisplayedMnemonic('f');
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setLabelFor(dtFechaRegistro);
        jLabel5.setText("Fecha reservada:");

        dtFechaReservacion.setToolTipText("");
        dtFechaReservacion.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                dtFechaReservacionPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hora reservada:");

        txtHoraReservacion.setToolTipText("Inserte la hora de reservación");
        txtHoraReservacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(dtFechaReservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoraReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHoraReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtFechaReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraRegistro))
                            .addComponent(txtNombre)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtFechaRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtHoraRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago"));

        cboxAnticipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxAnticipo.setMnemonic('d');
        cboxAnticipo.setText("Deja anticipo de pago ");
        cboxAnticipo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cboxAnticipoActionPerformed(evt);
            }
        });

        cmbboxPorcentaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "60", "80", "90" }));
        cmbboxPorcentaje.setEnabled(false);
        cmbboxPorcentaje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbboxPorcentajeActionPerformed(evt);
            }
        });

        labelPorcentaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPorcentaje.setText("% del total:");
        labelPorcentaje.setEnabled(false);

        cboxDescuentoEmpresas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxDescuentoEmpresas.setMnemonic('a');
        cboxDescuentoEmpresas.setText("Aplica descuento a empresa");
        cboxDescuentoEmpresas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cboxDescuentoEmpresasActionPerformed(evt);
            }
        });

        labelNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNombreEmpresa.setText("Empresa:");
        labelNombreEmpresa.setEnabled(false);

        txtEmpresa.setEnabled(false);

        btnEmpresas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmpresas.setText("F5");
        btnEmpresas.setEnabled(false);
        btnEmpresas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEmpresasActionPerformed(evt);
            }
        });

        labelDescuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDescuento.setForeground(new java.awt.Color(153, 0, 0));
        labelDescuento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDescuento.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboxAnticipo)
                .addGap(18, 18, 18)
                .addComponent(labelPorcentaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbboxPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(cboxDescuentoEmpresas)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelNombreEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpresas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAnticipo)
                    .addComponent(labelPorcentaje)
                    .addComponent(cmbboxPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxDescuentoEmpresas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreEmpresa)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpresas)
                    .addComponent(labelDescuento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Reservar (F3)");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar (F4)");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("TOTALES"));

        labelSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSubTotal.setText("   SubTotal:");

        txtSubTotal.setEditable(false);
        txtSubTotal.setForeground(new java.awt.Color(0, 51, 255));
        txtSubTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtSubTotal.setCaretColor(new java.awt.Color(51, 51, 255));
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        labelEtiqDescuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEtiqDescuento.setText(" - Descuento:");

        txtDescuento.setEditable(false);
        txtDescuento.setForeground(new java.awt.Color(51, 153, 0));
        txtDescuento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtDescuento.setCaretColor(new java.awt.Color(0, 153, 51));
        txtDescuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        labelTotalAPagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotalAPagar.setText("= Total a pagar:");

        txtTotal.setEditable(false);
        txtTotal.setForeground(new java.awt.Color(204, 0, 0));
        txtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtTotal.setCaretColor(new java.awt.Color(204, 0, 0));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        labelAnticipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAnticipo.setText("Anticipo:");
        labelAnticipo.setEnabled(false);

        txtAnticipo.setEditable(false);
        txtAnticipo.setForeground(new java.awt.Color(102, 0, 153));
        txtAnticipo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtAnticipo.setEnabled(false);
        txtAnticipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSubTotal)
                    .addComponent(labelEtiqDescuento)
                    .addComponent(labelTotalAPagar)
                    .addComponent(labelAnticipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnticipo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEtiqDescuento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalAPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAnticipo)
                    .addComponent(txtAnticipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnListarReservaciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarReservaciones.setText("Reservaciones (F1)");
        btnListarReservaciones.setToolTipText("Ver fechas reservadas");
        btnListarReservaciones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnListarReservacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarReservaciones)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnCancelar)
                            .addComponent(btnListarReservaciones)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cboxAnticipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxAnticipoActionPerformed
        // TODO add your handling code here:                
        boolean bAnticipo = false;
        
        bAnticipo = cboxAnticipo.isSelected();
        labelPorcentaje.setEnabled(bAnticipo);
        cmbboxPorcentaje.setEnabled(bAnticipo);
        labelAnticipo.setEnabled(bAnticipo);
        txtAnticipo.setEnabled(bAnticipo);
        labelSubTotal.setEnabled(!bAnticipo);
        txtSubTotal.setEnabled(!bAnticipo);
        labelEtiqDescuento.setEnabled(!bAnticipo);
        txtDescuento.setEnabled(!bAnticipo);
        labelDescuento.setEnabled(!bAnticipo);
        labelTotalAPagar.setEnabled(!bAnticipo);
        txtTotal.setEnabled(!bAnticipo); 
        RecalculaTotalBoton(0);
    }//GEN-LAST:event_cboxAnticipoActionPerformed

    public int CalculaAnticipo()
    {
        int iPorcentaje = 0;
        boolean bAnticipo = false;
        
        bAnticipo = cboxAnticipo.isSelected();        
        
        if ( bAnticipo )
        {
            iPorcentaje = Integer.parseInt(cmbboxPorcentaje.getItemAt(cmbboxPorcentaje.getSelectedIndex()).toString());            
        }
        
        return iPorcentaje;
    }
    
    private void btnPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteActionPerformed
        // TODO add your handling code here:
        MuestraListaPaquetes();
    }//GEN-LAST:event_btnPaqueteActionPerformed

    private void btnSoloSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoloSalaActionPerformed
        // TODO add your handling code here:
        RecalculaTotalBoton(1);
    }//GEN-LAST:event_btnSoloSalaActionPerformed

    private void btnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffeeActionPerformed
        // TODO add your handling code here:
        RecalculaTotalBoton(2);
    }//GEN-LAST:event_btnCoffeeActionPerformed

    private void btnAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmuerzoActionPerformed
        // TODO add your handling code here:
        RecalculaTotalBoton(3);
    }//GEN-LAST:event_btnAlmuerzoActionPerformed

    private void txtTotalPersonasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPersonasKeyTyped
        // TODO add your handling code here:
         char cCaracter = evt.getKeyChar();        
        
        // Verificar si la tecla pulsada no es un digito        
        if ( !Character.isDigit(cCaracter) /*|| cCaracter == '0'*/ )
        {
            evt.consume();  // ignorar el evento de teclado
        }       
    }//GEN-LAST:event_txtTotalPersonasKeyTyped

    private void txtTotalPersonasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPersonasKeyReleased
        // TODO add your handling code here:        
        char cCaracter = evt.getKeyChar();                  
                
        if ( Character.isDigit(cCaracter) )
        {                        
            RecalculaTotalBoton(0);                        
        }      
    }//GEN-LAST:event_txtTotalPersonasKeyReleased

    private void txtTotalPersonasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalPersonasFocusLost
        // TODO add your handling code here:
        int iTotalPersonas = 0;
        
        try
        {
            iTotalPersonas = Integer.parseInt(txtTotalPersonas.getText());
        }
        catch ( Exception e )
        {
            iTotalPersonas = 30;
        }
        
        if ( iTotalPersonas >= 30 )
        {
            RecalculaTotalBoton(0);
        }
        else
        {             
            uAccesibilidad.MuestraMensaje("La cantidad de personas es de mínimo 30.");
            txtTotalPersonas.requestFocus();
            txtTotalPersonas.setText("30");
            txtTotalPersonas.selectAll();
        }
    }//GEN-LAST:event_txtTotalPersonasFocusLost

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        ReservarSalaDeConferencias();        
    }//GEN-LAST:event_btnAceptarActionPerformed

    public boolean DatosClienteLlenos()
    {
        boolean bOk = true;
        
        if ( txtNombre.getText().isEmpty() )
        {
            bOk = false;
        }
        
        return bOk;
    }

    public boolean CamposReservacionLlenos()
    {
        boolean bOk = false;
        
        if ( dtFechaReservacion != null )
        {
            if ( dtFechaReservacion.getDate() != null )
            {                                
                if ( !txtHoraReservacion.getTimeField().getText().isEmpty() )
                {
                    bOk = true;
                }
            }
        }
        
        return bOk;
    }
    
    public boolean PaqueteSeleccionado()
    {
        boolean bOk = false;
        
        if ( !txtPaquete.getText().isEmpty() )
        {
            bOk = true;
        }
        
        return bOk;
    }
    
    public boolean DescuentoEmpresaLleno()
    {
        boolean bOk = false;
        
        if ( cboxDescuentoEmpresas.isSelected() )
        {
            if ( !txtEmpresa.getText().isEmpty() )
            {
                bOk = true;
            }
        }
        else
        {
            bOk = true;
        }
        
        return bOk;
    }        
    
    public void InstanciaDatos()
    {
        double dTotalAnticipo = 0.0;
        double dDescuento = 0.0;
        double dTotal = 0.0;
        
        scSala.setNombre(txtNombre.getText());
        scSala.setPaquete(pPaquete.getID());
        scSala.setFechaReservada(dtFechaReservacion.getDate());
        scSala.setHoraReservada(txtHoraReservacion.getTimeField().getText());
        scSala.setTiempoReservado(Integer.parseInt(txtTiempoReservado.getText()));
        scSala.setAnticipo(cboxAnticipo.isSelected() ? 1 : 0);
                            
        if ( cboxAnticipo.isSelected() )
        {
            dTotalAnticipo = 0.0;
                                
            if ( !txtAnticipo.getText().isEmpty()  )
            {
                dTotalAnticipo = Double.parseDouble(txtAnticipo.getText());
            }
        }
                            
        scSala.setTotalAnticipo(dTotalAnticipo);                            
        dTotal = 0.0;
                            
        if ( !txtTotal.getText().isEmpty() )
        {
            dTotal = Double.parseDouble(txtTotal.getText());
        }
                            
        scSala.setTotal(dTotal);
        scSala.setCantPersonas(Integer.parseInt(txtTotalPersonas.getText()));                            
                            
        if ( cboxDescuentoEmpresas.isSelected() )
        {
            dDescuento = 0.0;
                                
            if ( !txtDescuento.getText().isEmpty() )
            {
                dDescuento = Double.parseDouble(txtDescuento.getText());
            }
                                
            scSala.setEmpresa(this.Empresa);
        }
                            
        scSala.setTotDescuento(dDescuento);
        scSala.setSaldo(dTotal - dTotalAnticipo);
    }
    
    public void ReservarSalaDeConferencias()
    {                
        if ( DatosClienteLlenos() )
        {
            if ( CamposReservacionLlenos() )
            {
                if ( PaqueteSeleccionado() )
                {
                    if ( DescuentoEmpresaLleno() )
                    {
                        if ( uAccesibilidad.MuestraMensajeConfirmacion("¿Realmente deseas agregar esta reservación?") == 0 )
                        {
                            InstanciaDatos();
                            
                            if ( ValidaDatosInsertados() )
                            {                            
                                if ( scSala.Insertar() )
                                {
                                    uAccesibilidad.MuestraMensaje("Se ha reservado correctamente la Sala de Conferencias.");
                                    this.dispose();
                                }
                                else
                                {
                                    uAccesibilidad.MuestraMensaje("Ocurrió un error al tratar de Insertar en la Base de Datos.");
                                }
                            }
                        }
                    }
                    else
                    {
                        uAccesibilidad.MuestraMensaje("Es necesario seleccionar una Empresa para aplicar Descuento.");
                    }
                }
                else
                {
                    uAccesibilidad.MuestraMensaje("Es necesario seleccionar un paquete para la Sala de Conferencias.");    
                }
            }
            else
            {
                uAccesibilidad.MuestraMensaje("Se debe seleccionar una fecha y/o una hora para la reservación.");
            }
        }
        else
        {
            uAccesibilidad.MuestraMensaje("Se debe capturar el Nombre o Razón Social.");
            txtNombre.requestFocus();
            txtNombre.selectAll();
        }                
    }
    
    private void cmbboxPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxPorcentajeActionPerformed
        // TODO add your handling code here:
        RecalculaTotalBoton(0);
    }//GEN-LAST:event_cmbboxPorcentajeActionPerformed

    private void btnEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasActionPerformed
        // TODO add your handling code here:
        MuestraListaEmpresasDescuentos();
    }//GEN-LAST:event_btnEmpresasActionPerformed

    public void MuestraListaEmpresasDescuentos()
    {
        FrmListaEmpresas frm = new FrmListaEmpresas(null, true);
        
        frm.show(true);        
        txtEmpresa.setText(frm.getNombreEmpresa());
        labelDescuento.setText(String.valueOf(frm.getDescuento()) + "%");        
        this.Descuento = frm.getDescuento();
        this.Empresa = frm.getIDEmpresa();
        RecalculaTotalBoton(0);
    }
    
    private void cboxDescuentoEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDescuentoEmpresasActionPerformed
        // TODO add your handling code here:        
        HabilitaDeshEmpresa(cboxDescuentoEmpresas.isSelected());
    }//GEN-LAST:event_cboxDescuentoEmpresasActionPerformed

    private void dtFechaReservacionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtFechaReservacionPropertyChange
        // TODO add your handling code here:
        //RevisarFechaDisponible();
    }//GEN-LAST:event_dtFechaReservacionPropertyChange

    private void btnListarReservacionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnListarReservacionesActionPerformed
    {//GEN-HEADEREND:event_btnListarReservacionesActionPerformed
        // TODO add your handling code here:
        RevisarFechaDisponible();
    }//GEN-LAST:event_btnListarReservacionesActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyPressed
    {//GEN-HEADEREND:event_txtNombreKeyPressed
        // TODO add your handling code here:
        if ( uAccesibilidad.PresionoENTER(evt) )
        {
            txtTotalPersonas.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    public void RevisarFechaDisponible()
    {
        CnsReservacionesSalaConf frm = new CnsReservacionesSalaConf(null, true);
        
        frm.show();
    }
    
    public void HabilitaDeshEmpresa(boolean bActivar)
    {
        labelNombreEmpresa.setEnabled(bActivar);
        btnEmpresas.setEnabled(bActivar);
        
        if ( !bActivar )
        {            
            txtEmpresa.setText(null);
            txtDescuento.setText("0");
            labelDescuento.setText("0 %");
            this.Descuento = 0.0;
            RecalculaTotalBoton(0);
        }        
    }
    
    public void RecalculaTotalBoton(int iOpcion)
    {
        int iTotalPersonas = 1;        
        double dPrecio = 0.0;        
        double dTotal = 0.0;        
        double dAnticipo = 0.0;
        double dDescuento = 0.0;
        double dPorcentajeDescuento = 0.0;
        
        if ( pPaquete != null )
        {
             if ( iOpcion == 0 )
             {
                if ( btnSoloSala.isSelected() )
                {
                    iOpcion = 1;
                }
                else if ( btnCoffee.isSelected() )
                {
                    iOpcion = 2;
                }
                else if ( btnAlmuerzo.isSelected() )
                {
                    iOpcion = 3;
                }               
             }
            
            switch ( iOpcion )
            {               
                case 1:
                    dPrecio = pPaquete.getPrecioSala();
                break;
                case 2:
                    dPrecio = pPaquete.getPrecioCoffee();
                break;
                case 3:                    
                    iTotalPersonas = Integer.parseInt(txtTotalPersonas.getText());
                    dPrecio = ( pPaquete.getPrecioAlmuerzoPP() * iTotalPersonas );
                break;
                default:
                    dPrecio = pPaquete.getPrecioSala();
            }
        }
        
        txtSubTotal.setText(String.valueOf(dPrecio));
        //dTotal = dPrecio * iTotalPersonas;
        dTotal = dPrecio;
        
        if ( cboxAnticipo.isSelected() )
        {
            dAnticipo = ( dTotal * CalculaAnticipo() ) / 100;
        }
        
        if ( cboxDescuentoEmpresas.isSelected() )
        {
            dPorcentajeDescuento = this.Descuento;
            dDescuento =  ( dTotal * dPorcentajeDescuento ) / 100;
            txtDescuento.setText(String.valueOf(dDescuento));
            dTotal -= dDescuento;
        }
        
        txtAnticipo.setText(String.valueOf(dAnticipo));
        txtTotal.setText(String.valueOf(dTotal));        
    }
    
    public void MuestraListaPaquetes()
    {
        pPaquete = null;
        FrmListaPaquetes frm = new FrmListaPaquetes(null, true);
        
        frm.show();
        pPaquete = frm.getpPaquete();
        txtPaquete.setText(pPaquete.getDescripcion());
        txtTiempoReservado.setText(String.valueOf(pPaquete.getHoras()));
        txtTotalPersonas.setText("30");
        txtPrecioSala.setText(String.valueOf(pPaquete.getPrecioSala()));
        txtPrecioCoffe.setText(String.valueOf(pPaquete.getPrecioCoffee()));
        txtPrecioPorPersona.setText(String.valueOf(pPaquete.getPrecioAlmuerzoPP()));
        RecalculaTotalBoton(0);        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReservarSalaConferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReservarSalaConferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReservarSalaConferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReservarSalaConferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmReservarSalaConferencias dialog = new FrmReservarSalaConferencias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGrupo;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JRadioButton btnAlmuerzo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JRadioButton btnCoffee;
    private javax.swing.JButton btnEmpresas;
    private javax.swing.JButton btnListarReservaciones;
    private javax.swing.JButton btnPaquete;
    private javax.swing.JRadioButton btnSoloSala;
    private javax.swing.JCheckBox cboxAnticipo;
    private javax.swing.JCheckBox cboxDescuentoEmpresas;
    private javax.swing.JComboBox cmbboxPorcentaje;
    private com.toedter.calendar.JDateChooser dtFechaRegistro;
    private com.toedter.calendar.JDateChooser dtFechaReservacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private lu.tudor.santec.jtimechooser.demo.JTimeChooserDemo jTimeChooserDemo1;
    private javax.swing.JLabel labelAnticipo;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelEtiqDescuento;
    private javax.swing.JLabel labelNombreEmpresa;
    private javax.swing.JLabel labelPorcentaje;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelSubTotal1;
    private javax.swing.JLabel labelSubTotal2;
    private javax.swing.JLabel labelSubTotal3;
    private javax.swing.JLabel labelTotalAPagar;
    private javax.swing.JFormattedTextField txtAnticipo;
    private javax.swing.JFormattedTextField txtDescuento;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JFormattedTextField txtHoraRegistro;
    private lu.tudor.santec.jtimechooser.JTimeChooser txtHoraReservacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaquete;
    private javax.swing.JFormattedTextField txtPrecioCoffe;
    private javax.swing.JFormattedTextField txtPrecioPorPersona;
    private javax.swing.JFormattedTextField txtPrecioSala;
    private javax.swing.JFormattedTextField txtSubTotal;
    private javax.swing.JTextField txtTiempoReservado;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JTextField txtTotalPersonas;
    // End of variables declaration//GEN-END:variables

    public boolean ValidaDatosInsertados()
    {
        boolean bOk = true;
        
        if ( scSala.FechaReservada(this.scSala.getFechaReservada()) )
        {
            //Verificar la hora para ver si no chocan.
            if ( scSala.ChoqueDeHoraReservada(dtFechaReservacion.getDate(), txtHoraReservacion.getTimeField().getText(), Integer.parseInt(txtTiempoReservado.getText())) )
            {
                bOk = false;
            }
        }        
        
        return bOk;
    }
}
